export interface Airport {
  code: string;
  name: string;
  city: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  // United States — major international hubs
  { code: 'JFK', name: 'John F. Kennedy International', city: 'New York', country: 'United States' },
  { code: 'LGA', name: 'LaGuardia', city: 'New York', country: 'United States' },
  { code: 'EWR', name: 'Newark Liberty International', city: 'Newark', country: 'United States' },
  { code: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'United States' },
  { code: 'ORD', name: "O'Hare International", city: 'Chicago', country: 'United States' },
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International', city: 'Atlanta', country: 'United States' },
  { code: 'DFW', name: 'Dallas/Fort Worth International', city: 'Dallas', country: 'United States' },
  { code: 'SFO', name: 'San Francisco International', city: 'San Francisco', country: 'United States' },
  { code: 'MIA', name: 'Miami International', city: 'Miami', country: 'United States' },
  { code: 'SEA', name: 'Seattle-Tacoma International', city: 'Seattle', country: 'United States' },
  { code: 'BOS', name: 'Logan International', city: 'Boston', country: 'United States' },
  { code: 'DEN', name: 'Denver International', city: 'Denver', country: 'United States' },
  { code: 'IAH', name: 'George Bush Intercontinental', city: 'Houston', country: 'United States' },
  { code: 'MSP', name: 'Minneapolis-Saint Paul International', city: 'Minneapolis', country: 'United States' },
  { code: 'DTW', name: 'Detroit Metropolitan', city: 'Detroit', country: 'United States' },
  { code: 'PHX', name: 'Phoenix Sky Harbor International', city: 'Phoenix', country: 'United States' },
  { code: 'MCO', name: 'Orlando International', city: 'Orlando', country: 'United States' },
  { code: 'PHL', name: 'Philadelphia International', city: 'Philadelphia', country: 'United States' },
  { code: 'DCA', name: 'Ronald Reagan Washington National', city: 'Washington', country: 'United States' },
  { code: 'IAD', name: 'Washington Dulles International', city: 'Washington', country: 'United States' },
  // United States — domestic, regional and local airfields
  { code: 'HOU', name: 'William P. Hobby', city: 'Houston', country: 'United States' },
  { code: 'DAL', name: 'Dallas Love Field', city: 'Dallas', country: 'United States' },
  { code: 'AUS', name: 'Austin-Bergstrom International', city: 'Austin', country: 'United States' },
  { code: 'SAT', name: 'San Antonio International', city: 'San Antonio', country: 'United States' },
  { code: 'ELP', name: 'El Paso International', city: 'El Paso', country: 'United States' },
  { code: 'LBB', name: 'Lubbock Preston Smith International', city: 'Lubbock', country: 'United States' },
  { code: 'AMA', name: 'Rick Husband Amarillo International', city: 'Amarillo', country: 'United States' },
  { code: 'CRP', name: 'Corpus Christi International', city: 'Corpus Christi', country: 'United States' },
  { code: 'MFE', name: 'McAllen Miller International', city: 'McAllen', country: 'United States' },
  { code: 'HRL', name: 'Valley International', city: 'Harlingen', country: 'United States' },
  { code: 'BWI', name: 'Baltimore/Washington International', city: 'Baltimore', country: 'United States' },
  { code: 'CLT', name: 'Charlotte Douglas International', city: 'Charlotte', country: 'United States' },
  { code: 'RDU', name: 'Raleigh-Durham International', city: 'Raleigh', country: 'United States' },
  { code: 'GSO', name: 'Piedmont Triad International', city: 'Greensboro', country: 'United States' },
  { code: 'AVL', name: 'Asheville Regional', city: 'Asheville', country: 'United States' },
  { code: 'ILM', name: 'Wilmington International', city: 'Wilmington', country: 'United States' },
  { code: 'CHS', name: 'Charleston International', city: 'Charleston', country: 'United States' },
  { code: 'CAE', name: 'Columbia Metropolitan', city: 'Columbia', country: 'United States' },
  { code: 'MYR', name: 'Myrtle Beach International', city: 'Myrtle Beach', country: 'United States' },
  { code: 'GSP', name: 'Greenville-Spartanburg International', city: 'Greenville', country: 'United States' },
  { code: 'SAV', name: 'Savannah/Hilton Head International', city: 'Savannah', country: 'United States' },
  { code: 'JAX', name: 'Jacksonville International', city: 'Jacksonville', country: 'United States' },
  { code: 'TLH', name: 'Tallahassee International', city: 'Tallahassee', country: 'United States' },
  { code: 'PNS', name: 'Pensacola International', city: 'Pensacola', country: 'United States' },
  { code: 'TPA', name: 'Tampa International', city: 'Tampa', country: 'United States' },
  { code: 'PIE', name: 'St. Pete-Clearwater International', city: 'St. Petersburg', country: 'United States' },
  { code: 'RSW', name: 'Southwest Florida International', city: 'Fort Myers', country: 'United States' },
  { code: 'PBI', name: 'Palm Beach International', city: 'West Palm Beach', country: 'United States' },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood International', city: 'Fort Lauderdale', country: 'United States' },
  { code: 'KEY', name: 'Key West International', city: 'Key West', country: 'United States' },
  { code: 'EYW', name: 'Key West International (regional)', city: 'Key West', country: 'United States' },
  { code: 'BNA', name: 'Nashville International', city: 'Nashville', country: 'United States' },
  { code: 'MEM', name: 'Memphis International', city: 'Memphis', country: 'United States' },
  { code: 'TYS', name: 'McGhee Tyson', city: 'Knoxville', country: 'United States' },
  { code: 'CHA', name: 'Chattanooga Metropolitan', city: 'Chattanooga', country: 'United States' },
  { code: 'BHM', name: 'Birmingham-Shuttlesworth International', city: 'Birmingham', country: 'United States' },
  { code: 'HSV', name: 'Huntsville International', city: 'Huntsville', country: 'United States' },
  { code: 'MOB', name: 'Mobile Regional', city: 'Mobile', country: 'United States' },
  { code: 'MGM', name: 'Montgomery Regional', city: 'Montgomery', country: 'United States' },
  { code: 'JAN', name: 'Jackson-Medgar Wiley Evers International', city: 'Jackson', country: 'United States' },
  { code: 'GPT', name: 'Gulfport-Biloxi International', city: 'Gulfport', country: 'United States' },
  { code: 'MSY', name: 'Louis Armstrong New Orleans International', city: 'New Orleans', country: 'United States' },
  { code: 'BTR', name: 'Baton Rouge Metropolitan', city: 'Baton Rouge', country: 'United States' },
  { code: 'SHV', name: 'Shreveport Regional', city: 'Shreveport', country: 'United States' },
  { code: 'LFT', name: 'Lafayette Regional', city: 'Lafayette', country: 'United States' },
  { code: 'LIT', name: 'Bill and Hillary Clinton National', city: 'Little Rock', country: 'United States' },
  { code: 'XNA', name: 'Northwest Arkansas National', city: 'Bentonville', country: 'United States' },
  { code: 'OKC', name: 'Will Rogers World', city: 'Oklahoma City', country: 'United States' },
  { code: 'TUL', name: 'Tulsa International', city: 'Tulsa', country: 'United States' },
  { code: 'STL', name: 'St. Louis Lambert International', city: 'St. Louis', country: 'United States' },
  { code: 'MCI', name: 'Kansas City International', city: 'Kansas City', country: 'United States' },
  { code: 'ICT', name: 'Wichita Dwight D. Eisenhower National', city: 'Wichita', country: 'United States' },
  { code: 'OMA', name: 'Eppley Airfield', city: 'Omaha', country: 'United States' },
  { code: 'LNK', name: 'Lincoln', city: 'Lincoln', country: 'United States' },
  { code: 'DSM', name: 'Des Moines International', city: 'Des Moines', country: 'United States' },
  { code: 'CID', name: 'Cedar Rapids', city: 'Cedar Rapids', country: 'United States' },
  { code: 'MKE', name: 'Milwaukee Mitchell International', city: 'Milwaukee', country: 'United States' },
  { code: 'MSN', name: 'Dane County Regional', city: 'Madison', country: 'United States' },
  { code: 'GRB', name: 'Green Bay Austin Straubel', city: 'Green Bay', country: 'United States' },
  { code: 'IND', name: 'Indianapolis International', city: 'Indianapolis', country: 'United States' },
  { code: 'FWA', name: 'Fort Wayne International', city: 'Fort Wayne', country: 'United States' },
  { code: 'EVV', name: 'Evansville Regional', city: 'Evansville', country: 'United States' },
  { code: 'CMH', name: 'John Glenn Columbus International', city: 'Columbus', country: 'United States' },
  { code: 'CLE', name: 'Cleveland Hopkins International', city: 'Cleveland', country: 'United States' },
  { code: 'CAK', name: 'Akron-Canton', city: 'Akron', country: 'United States' },
  { code: 'TOL', name: 'Toledo Express', city: 'Toledo', country: 'United States' },
  { code: 'DAY', name: 'Dayton International', city: 'Dayton', country: 'United States' },
  { code: 'CVG', name: 'Cincinnati/Northern Kentucky International', city: 'Cincinnati', country: 'United States' },
  { code: 'SDF', name: 'Louisville Muhammad Ali International', city: 'Louisville', country: 'United States' },
  { code: 'LEX', name: 'Blue Grass', city: 'Lexington', country: 'United States' },
  { code: 'CRW', name: 'Yeager', city: 'Charleston (WV)', country: 'United States' },
  { code: 'PIT', name: 'Pittsburgh International', city: 'Pittsburgh', country: 'United States' },
  { code: 'ERI', name: 'Erie International', city: 'Erie', country: 'United States' },
  { code: 'BUF', name: 'Buffalo Niagara International', city: 'Buffalo', country: 'United States' },
  { code: 'ROC', name: 'Greater Rochester International', city: 'Rochester', country: 'United States' },
  { code: 'SYR', name: 'Syracuse Hancock International', city: 'Syracuse', country: 'United States' },
  { code: 'ALB', name: 'Albany International', city: 'Albany', country: 'United States' },
  { code: 'BTV', name: 'Burlington International', city: 'Burlington', country: 'United States' },
  { code: 'PWM', name: 'Portland International Jetport', city: 'Portland (ME)', country: 'United States' },
  { code: 'BGR', name: 'Bangor International', city: 'Bangor', country: 'United States' },
  { code: 'MHT', name: 'Manchester-Boston Regional', city: 'Manchester', country: 'United States' },
  { code: 'PVD', name: 'T. F. Green', city: 'Providence', country: 'United States' },
  { code: 'BDL', name: 'Bradley International', city: 'Hartford', country: 'United States' },
  { code: 'HPN', name: 'Westchester County', city: 'White Plains', country: 'United States' },
  { code: 'ISP', name: 'Long Island MacArthur', city: 'Islip', country: 'United States' },
  { code: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', country: 'United States' },
  { code: 'SAF', name: 'Santa Fe Regional', city: 'Santa Fe', country: 'United States' },
  { code: 'TUS', name: 'Tucson International', city: 'Tucson', country: 'United States' },
  { code: 'FLG', name: 'Flagstaff Pulliam', city: 'Flagstaff', country: 'United States' },
  { code: 'YUM', name: 'Yuma International', city: 'Yuma', country: 'United States' },
  { code: 'SLC', name: 'Salt Lake City International', city: 'Salt Lake City', country: 'United States' },
  { code: 'PVU', name: 'Provo Municipal', city: 'Provo', country: 'United States' },
  { code: 'BIL', name: 'Billings Logan International', city: 'Billings', country: 'United States' },
  { code: 'BZN', name: 'Bozeman Yellowstone International', city: 'Bozeman', country: 'United States' },
  { code: 'MSO', name: 'Missoula Montana', city: 'Missoula', country: 'United States' },
  { code: 'GTF', name: 'Great Falls International', city: 'Great Falls', country: 'United States' },
  { code: 'BOI', name: 'Boise Airport', city: 'Boise', country: 'United States' },
  { code: 'GEG', name: 'Spokane International', city: 'Spokane', country: 'United States' },
  { code: 'PSC', name: 'Tri-Cities', city: 'Pasco', country: 'United States' },
  { code: 'YKM', name: 'Yakima Air Terminal', city: 'Yakima', country: 'United States' },
  { code: 'PDX', name: 'Portland International', city: 'Portland (OR)', country: 'United States' },
  { code: 'EUG', name: 'Mahlon Sweet Field', city: 'Eugene', country: 'United States' },
  { code: 'MFR', name: 'Rogue Valley International-Medford', city: 'Medford', country: 'United States' },
  { code: 'RDM', name: 'Roberts Field', city: 'Redmond', country: 'United States' },
  { code: 'OAK', name: 'Oakland International', city: 'Oakland', country: 'United States' },
  { code: 'SJC', name: 'Norman Y. Mineta San José International', city: 'San Jose', country: 'United States' },
  { code: 'SMF', name: 'Sacramento International', city: 'Sacramento', country: 'United States' },
  { code: 'SAN', name: 'San Diego International', city: 'San Diego', country: 'United States' },
  { code: 'SNA', name: 'John Wayne (Orange County)', city: 'Santa Ana', country: 'United States' },
  { code: 'BUR', name: 'Hollywood Burbank', city: 'Burbank', country: 'United States' },
  { code: 'LGB', name: 'Long Beach', city: 'Long Beach', country: 'United States' },
  { code: 'ONT', name: 'Ontario International', city: 'Ontario', country: 'United States' },
  { code: 'PSP', name: 'Palm Springs International', city: 'Palm Springs', country: 'United States' },
  { code: 'FAT', name: 'Fresno Yosemite International', city: 'Fresno', country: 'United States' },
  { code: 'BFL', name: 'Meadows Field', city: 'Bakersfield', country: 'United States' },
  { code: 'SBA', name: 'Santa Barbara Municipal', city: 'Santa Barbara', country: 'United States' },
  { code: 'MRY', name: 'Monterey Regional', city: 'Monterey', country: 'United States' },
  { code: 'ACV', name: 'California Redwood Coast-Humboldt County', city: 'Arcata', country: 'United States' },
  { code: 'RDD', name: 'Redding Municipal', city: 'Redding', country: 'United States' },
  { code: 'STS', name: 'Charles M. Schulz-Sonoma County', city: 'Santa Rosa', country: 'United States' },
  { code: 'RNO', name: 'Reno-Tahoe International', city: 'Reno', country: 'United States' },
  { code: 'LAS', name: 'Harry Reid International', city: 'Las Vegas', country: 'United States' },
  { code: 'HNL', name: 'Daniel K. Inouye International', city: 'Honolulu', country: 'United States' },
  { code: 'OGG', name: 'Kahului', city: 'Maui', country: 'United States' },
  { code: 'KOA', name: 'Ellison Onizuka Kona International', city: 'Kona', country: 'United States' },
  { code: 'ITO', name: 'Hilo International', city: 'Hilo', country: 'United States' },
  { code: 'LIH', name: 'Lihue', city: 'Lihue', country: 'United States' },
  { code: 'MKK', name: 'Molokai', city: 'Hoolehua', country: 'United States' },
  { code: 'LNY', name: 'Lanai', city: 'Lanai City', country: 'United States' },
  { code: 'ANC', name: 'Ted Stevens Anchorage International', city: 'Anchorage', country: 'United States' },
  { code: 'FAI', name: 'Fairbanks International', city: 'Fairbanks', country: 'United States' },
  { code: 'JNU', name: 'Juneau International', city: 'Juneau', country: 'United States' },
  { code: 'SIT', name: 'Sitka Rocky Gutierrez', city: 'Sitka', country: 'United States' },
  { code: 'KTN', name: 'Ketchikan International', city: 'Ketchikan', country: 'United States' },
  { code: 'BET', name: 'Bethel', city: 'Bethel', country: 'United States' },
  { code: 'OME', name: 'Nome', city: 'Nome', country: 'United States' },
  { code: 'OTZ', name: 'Ralph Wien Memorial', city: 'Kotzebue', country: 'United States' },
  { code: 'BRW', name: 'Wiley Post-Will Rogers Memorial', city: 'Utqiagvik', country: 'United States' },
  { code: 'ADQ', name: 'Kodiak', city: 'Kodiak', country: 'United States' },
  { code: 'CDV', name: 'Merle K. (Mudhole) Smith', city: 'Cordova', country: 'United States' },
  { code: 'GUM', name: 'Antonio B. Won Pat International', city: 'Hagåtña', country: 'Guam' },
  { code: 'PPG', name: 'Pago Pago International', city: 'Pago Pago', country: 'American Samoa' },
  { code: 'SJU', name: 'Luis Muñoz Marín International', city: 'San Juan', country: 'Puerto Rico' },
  { code: 'BQN', name: 'Rafael Hernández', city: 'Aguadilla', country: 'Puerto Rico' },
  { code: 'PSE', name: 'Mercedita', city: 'Ponce', country: 'Puerto Rico' },
  { code: 'STT', name: 'Cyril E. King', city: 'Charlotte Amalie', country: 'United States Virgin Islands' },
  { code: 'STX', name: 'Henry E. Rohlsen', city: 'Saint Croix', country: 'United States Virgin Islands' },

  // Canada — domestic and regional
  { code: 'YYZ', name: 'Toronto Pearson International', city: 'Toronto', country: 'Canada' },
  { code: 'YTZ', name: 'Billy Bishop Toronto City', city: 'Toronto', country: 'Canada' },
  { code: 'YHM', name: 'John C. Munro Hamilton International', city: 'Hamilton', country: 'Canada' },
  { code: 'YKF', name: 'Region of Waterloo International', city: 'Kitchener', country: 'Canada' },
  { code: 'YQG', name: 'Windsor International', city: 'Windsor', country: 'Canada' },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International', city: 'Ottawa', country: 'Canada' },
  { code: 'YUL', name: 'Montréal-Trudeau International', city: 'Montreal', country: 'Canada' },
  { code: 'YQB', name: 'Québec City Jean Lesage International', city: 'Quebec City', country: 'Canada' },
  { code: 'YHZ', name: 'Halifax Stanfield International', city: 'Halifax', country: 'Canada' },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International', city: 'Moncton', country: 'Canada' },
  { code: 'YYG', name: 'Charlottetown', city: 'Charlottetown', country: 'Canada' },
  { code: 'YYT', name: "St. John's International", city: "St. John's", country: 'Canada' },
  { code: 'YDF', name: 'Deer Lake Regional', city: 'Deer Lake', country: 'Canada' },
  { code: 'YQX', name: 'Gander International', city: 'Gander', country: 'Canada' },
  { code: 'YFC', name: 'Fredericton International', city: 'Fredericton', country: 'Canada' },
  { code: 'YSJ', name: 'Saint John', city: 'Saint John', country: 'Canada' },
  { code: 'YVR', name: 'Vancouver International', city: 'Vancouver', country: 'Canada' },
  { code: 'YYJ', name: 'Victoria International', city: 'Victoria', country: 'Canada' },
  { code: 'YXS', name: 'Prince George', city: 'Prince George', country: 'Canada' },
  { code: 'YLW', name: 'Kelowna International', city: 'Kelowna', country: 'Canada' },
  { code: 'YYC', name: 'Calgary International', city: 'Calgary', country: 'Canada' },
  { code: 'YEG', name: 'Edmonton International', city: 'Edmonton', country: 'Canada' },
  { code: 'YQR', name: 'Regina International', city: 'Regina', country: 'Canada' },
  { code: 'YXE', name: 'Saskatoon John G. Diefenbaker International', city: 'Saskatoon', country: 'Canada' },
  { code: 'YWG', name: 'Winnipeg James Armstrong Richardson International', city: 'Winnipeg', country: 'Canada' },
  { code: 'YQT', name: 'Thunder Bay International', city: 'Thunder Bay', country: 'Canada' },
  { code: 'YZF', name: 'Yellowknife', city: 'Yellowknife', country: 'Canada' },
  { code: 'YXY', name: 'Erik Nielsen Whitehorse International', city: 'Whitehorse', country: 'Canada' },
  { code: 'YFB', name: 'Iqaluit', city: 'Iqaluit', country: 'Canada' },

  // Mexico — domestic and regional
  { code: 'MEX', name: 'Mexico City International', city: 'Mexico City', country: 'Mexico' },
  { code: 'NLU', name: 'Felipe Ángeles International', city: 'Mexico City', country: 'Mexico' },
  { code: 'TLC', name: 'Toluca International', city: 'Toluca', country: 'Mexico' },
  { code: 'GDL', name: 'Guadalajara International', city: 'Guadalajara', country: 'Mexico' },
  { code: 'MTY', name: 'Monterrey International', city: 'Monterrey', country: 'Mexico' },
  { code: 'TIJ', name: 'Tijuana International', city: 'Tijuana', country: 'Mexico' },
  { code: 'CUN', name: 'Cancún International', city: 'Cancun', country: 'Mexico' },
  { code: 'MID', name: 'Mérida International', city: 'Merida', country: 'Mexico' },
  { code: 'OAX', name: 'Xoxocotlán International', city: 'Oaxaca', country: 'Mexico' },
  { code: 'PVR', name: 'Licenciado Gustavo Díaz Ordaz International', city: 'Puerto Vallarta', country: 'Mexico' },
  { code: 'SJD', name: 'Los Cabos International', city: 'San José del Cabo', country: 'Mexico' },
  { code: 'BJX', name: 'Del Bajío International', city: 'León', country: 'Mexico' },
  { code: 'QRO', name: 'Querétaro Intercontinental', city: 'Querétaro', country: 'Mexico' },
  { code: 'SLP', name: 'Ponciano Arriaga International', city: 'San Luis Potosí', country: 'Mexico' },
  { code: 'CJS', name: 'Abraham González International', city: 'Ciudad Juárez', country: 'Mexico' },
  { code: 'MZT', name: 'General Rafael Buelna International', city: 'Mazatlán', country: 'Mexico' },
  { code: 'CUL', name: 'Federal de Bachigualato International', city: 'Culiacán', country: 'Mexico' },
  { code: 'HMO', name: 'General Ignacio Pesqueira García International', city: 'Hermosillo', country: 'Mexico' },
  { code: 'CZM', name: 'Cozumel International', city: 'Cozumel', country: 'Mexico' },
  { code: 'ZIH', name: 'Ixtapa-Zihuatanejo International', city: 'Zihuatanejo', country: 'Mexico' },
  { code: 'ACA', name: 'Acapulco International', city: 'Acapulco', country: 'Mexico' },
  { code: 'HUX', name: 'Bahías de Huatulco International', city: 'Huatulco', country: 'Mexico' },
  // Latin America — domestic and regional
  { code: 'GRU', name: 'São Paulo/Guarulhos International', city: 'Sao Paulo', country: 'Brazil' },
  { code: 'CGH', name: 'São Paulo/Congonhas', city: 'Sao Paulo', country: 'Brazil' },
  { code: 'VCP', name: 'Viracopos International', city: 'Campinas', country: 'Brazil' },
  { code: 'GIG', name: 'Rio de Janeiro/Galeão International', city: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'SDU', name: 'Santos Dumont', city: 'Rio de Janeiro', country: 'Brazil' },
  { code: 'BSB', name: 'Brasília-Presidente Juscelino Kubitschek International', city: 'Brasilia', country: 'Brazil' },
  { code: 'CNF', name: 'Belo Horizonte/Confins International', city: 'Belo Horizonte', country: 'Brazil' },
  { code: 'POA', name: 'Salgado Filho International', city: 'Porto Alegre', country: 'Brazil' },
  { code: 'CWB', name: 'Afonso Pena International', city: 'Curitiba', country: 'Brazil' },
  { code: 'FLN', name: 'Hercílio Luz International', city: 'Florianópolis', country: 'Brazil' },
  { code: 'SSA', name: 'Deputado Luís Eduardo Magalhães International', city: 'Salvador', country: 'Brazil' },
  { code: 'REC', name: 'Recife/Guararapes International', city: 'Recife', country: 'Brazil' },
  { code: 'FOR', name: 'Pinto Martins International', city: 'Fortaleza', country: 'Brazil' },
  { code: 'NAT', name: 'Greater Natal International', city: 'Natal', country: 'Brazil' },
  { code: 'BEL', name: 'Val de Cans International', city: 'Belém', country: 'Brazil' },
  { code: 'MAO', name: 'Eduardo Gomes International', city: 'Manaus', country: 'Brazil' },
  { code: 'CGB', name: 'Marechal Rondon International', city: 'Cuiabá', country: 'Brazil' },
  { code: 'CGR', name: 'Campo Grande International', city: 'Campo Grande', country: 'Brazil' },
  { code: 'IGU', name: 'Foz do Iguaçu International', city: 'Foz do Iguaçu', country: 'Brazil' },
  { code: 'EZE', name: 'Ministro Pistarini International', city: 'Buenos Aires', country: 'Argentina' },
  { code: 'AEP', name: 'Jorge Newbery Aeroparque', city: 'Buenos Aires', country: 'Argentina' },
  { code: 'COR', name: 'Ingeniero Ambrosio Taravella International', city: 'Córdoba', country: 'Argentina' },
  { code: 'MDZ', name: 'Governor Francisco Gabrielli International', city: 'Mendoza', country: 'Argentina' },
  { code: 'BRC', name: 'Teniente Luis Candelaria International', city: 'Bariloche', country: 'Argentina' },
  { code: 'USH', name: 'Ushuaia-Malvinas Argentinas International', city: 'Ushuaia', country: 'Argentina' },
  { code: 'SCL', name: 'Arturo Merino Benítez International', city: 'Santiago', country: 'Chile' },
  { code: 'CCP', name: 'Carriel Sur International', city: 'Concepción', country: 'Chile' },
  { code: 'IPC', name: 'Mataveri International', city: 'Easter Island', country: 'Chile' },
  { code: 'PUQ', name: 'Presidente Carlos Ibáñez del Campo International', city: 'Punta Arenas', country: 'Chile' },
  { code: 'BOG', name: 'El Dorado International', city: 'Bogotá', country: 'Colombia' },
  { code: 'MDE', name: 'José María Córdova International', city: 'Medellín', country: 'Colombia' },
  { code: 'CTG', name: 'Rafael Núñez International', city: 'Cartagena', country: 'Colombia' },
  { code: 'CLO', name: 'Alfonso Bonilla Aragón International', city: 'Cali', country: 'Colombia' },
  { code: 'BAQ', name: 'Ernesto Cortissoz International', city: 'Barranquilla', country: 'Colombia' },
  { code: 'SMR', name: 'Simón Bolívar International', city: 'Santa Marta', country: 'Colombia' },
  { code: 'LIM', name: 'Jorge Chávez International', city: 'Lima', country: 'Peru' },
  { code: 'CUZ', name: 'Alejandro Velasco Astete International', city: 'Cusco', country: 'Peru' },
  { code: 'AQP', name: 'Rodríguez Ballón International', city: 'Arequipa', country: 'Peru' },
  { code: 'IQT', name: 'Coronel FAP Francisco Secada Vignetta International', city: 'Iquitos', country: 'Peru' },
  { code: 'TRU', name: 'Capitán FAP Carlos Martínez de Pinillos International', city: 'Trujillo', country: 'Peru' },
  { code: 'UIO', name: 'Mariscal Sucre International', city: 'Quito', country: 'Ecuador' },
  { code: 'GYE', name: 'José Joaquín de Olmedo International', city: 'Guayaquil', country: 'Ecuador' },
  { code: 'GPS', name: 'Seymour', city: 'Galápagos', country: 'Ecuador' },
  { code: 'CCS', name: 'Simón Bolívar International', city: 'Caracas', country: 'Venezuela' },
  { code: 'MAR', name: 'La Chinita International', city: 'Maracaibo', country: 'Venezuela' },
  { code: 'PMV', name: 'Santiago Mariño Caribbean International', city: 'Porlamar', country: 'Venezuela' },
  { code: 'LPB', name: 'El Alto International', city: 'La Paz', country: 'Bolivia' },
  { code: 'VVI', name: 'Viru Viru International', city: 'Santa Cruz', country: 'Bolivia' },
  { code: 'ASU', name: 'Silvio Pettirossi International', city: 'Asunción', country: 'Paraguay' },
  { code: 'MVD', name: 'Carrasco International', city: 'Montevideo', country: 'Uruguay' },
  { code: 'PTY', name: 'Tocumen International', city: 'Panama City', country: 'Panama' },
  { code: 'PAC', name: 'Marcos A. Gelabert International', city: 'Panama City', country: 'Panama' },
  { code: 'SJO', name: 'Juan Santamaría International', city: 'San Jose', country: 'Costa Rica' },
  { code: 'LIR', name: 'Daniel Oduber Quirós International', city: 'Liberia', country: 'Costa Rica' },
  { code: 'MGA', name: 'Augusto C. Sandino International', city: 'Managua', country: 'Nicaragua' },
  { code: 'TGU', name: 'Toncontín International', city: 'Tegucigalpa', country: 'Honduras' },
  { code: 'SAP', name: 'Ramón Villeda Morales International', city: 'San Pedro Sula', country: 'Honduras' },
  { code: 'RTB', name: 'Juan Manuel Gálvez International', city: 'Roatán', country: 'Honduras' },
  { code: 'SAL', name: 'San Salvador International', city: 'San Salvador', country: 'El Salvador' },
  { code: 'GUA', name: 'La Aurora International', city: 'Guatemala City', country: 'Guatemala' },
  { code: 'BZE', name: 'Philip S. W. Goldson International', city: 'Belize City', country: 'Belize' },
  { code: 'HAV', name: 'José Martí International', city: 'Havana', country: 'Cuba' },
  { code: 'VRA', name: 'Juan Gualberto Gómez', city: 'Varadero', country: 'Cuba' },
  { code: 'KIN', name: 'Norman Manley International', city: 'Kingston', country: 'Jamaica' },
  { code: 'MBJ', name: 'Sangster International', city: 'Montego Bay', country: 'Jamaica' },
  { code: 'NAS', name: 'Lynden Pindling International', city: 'Nassau', country: 'Bahamas' },
  { code: 'POP', name: 'Gregorio Luperón International', city: 'Puerto Plata', country: 'Dominican Republic' },
  { code: 'PUJ', name: 'Punta Cana International', city: 'Punta Cana', country: 'Dominican Republic' },
  { code: 'SDQ', name: 'Las Américas International', city: 'Santo Domingo', country: 'Dominican Republic' },
  { code: 'PAP', name: 'Toussaint Louverture International', city: 'Port-au-Prince', country: 'Haiti' },
  { code: 'AUA', name: 'Queen Beatrix International', city: 'Oranjestad', country: 'Aruba' },
  { code: 'CUR', name: 'Hato International', city: 'Willemstad', country: 'Curaçao' },
  { code: 'BGI', name: 'Grantley Adams International', city: 'Bridgetown', country: 'Barbados' },
  { code: 'POS', name: 'Piarco International', city: 'Port of Spain', country: 'Trinidad and Tobago' },
  // United Kingdom & Ireland — domestic, regional, local
  { code: 'LHR', name: 'London Heathrow', city: 'London', country: 'United Kingdom' },
  { code: 'LGW', name: 'London Gatwick', city: 'London', country: 'United Kingdom' },
  { code: 'STN', name: 'London Stansted', city: 'London', country: 'United Kingdom' },
  { code: 'LTN', name: 'London Luton', city: 'London', country: 'United Kingdom' },
  { code: 'LCY', name: 'London City', city: 'London', country: 'United Kingdom' },
  { code: 'SEN', name: 'London Southend', city: 'London', country: 'United Kingdom' },
  { code: 'MAN', name: 'Manchester', city: 'Manchester', country: 'United Kingdom' },
  { code: 'BHX', name: 'Birmingham', city: 'Birmingham', country: 'United Kingdom' },
  { code: 'BRS', name: 'Bristol', city: 'Bristol', country: 'United Kingdom' },
  { code: 'NCL', name: 'Newcastle', city: 'Newcastle', country: 'United Kingdom' },
  { code: 'LBA', name: 'Leeds Bradford', city: 'Leeds', country: 'United Kingdom' },
  { code: 'LPL', name: 'Liverpool John Lennon', city: 'Liverpool', country: 'United Kingdom' },
  { code: 'EMA', name: 'East Midlands', city: 'Nottingham', country: 'United Kingdom' },
  { code: 'NWI', name: 'Norwich International', city: 'Norwich', country: 'United Kingdom' },
  { code: 'EXT', name: 'Exeter', city: 'Exeter', country: 'United Kingdom' },
  { code: 'BOH', name: 'Bournemouth', city: 'Bournemouth', country: 'United Kingdom' },
  { code: 'SOU', name: 'Southampton', city: 'Southampton', country: 'United Kingdom' },
  { code: 'CWL', name: 'Cardiff', city: 'Cardiff', country: 'United Kingdom' },
  { code: 'BFS', name: 'Belfast International', city: 'Belfast', country: 'United Kingdom' },
  { code: 'BHD', name: 'George Best Belfast City', city: 'Belfast', country: 'United Kingdom' },
  { code: 'LDY', name: 'City of Derry', city: 'Derry', country: 'United Kingdom' },
  { code: 'EDI', name: 'Edinburgh', city: 'Edinburgh', country: 'United Kingdom' },
  { code: 'GLA', name: 'Glasgow International', city: 'Glasgow', country: 'United Kingdom' },
  { code: 'PIK', name: 'Glasgow Prestwick', city: 'Glasgow', country: 'United Kingdom' },
  { code: 'ABZ', name: 'Aberdeen International', city: 'Aberdeen', country: 'United Kingdom' },
  { code: 'INV', name: 'Inverness', city: 'Inverness', country: 'United Kingdom' },
  { code: 'KOI', name: 'Kirkwall', city: 'Kirkwall', country: 'United Kingdom' },
  { code: 'LSI', name: 'Sumburgh', city: 'Shetland', country: 'United Kingdom' },
  { code: 'IOM', name: 'Isle of Man', city: 'Isle of Man', country: 'United Kingdom' },
  { code: 'JER', name: 'Jersey', city: 'Saint Helier', country: 'Jersey' },
  { code: 'GCI', name: 'Guernsey', city: 'Saint Peter Port', country: 'Guernsey' },
  { code: 'DUB', name: 'Dublin', city: 'Dublin', country: 'Ireland' },
  { code: 'ORK', name: 'Cork', city: 'Cork', country: 'Ireland' },
  { code: 'SNN', name: 'Shannon', city: 'Shannon', country: 'Ireland' },
  { code: 'NOC', name: 'Ireland West Knock', city: 'Knock', country: 'Ireland' },
  { code: 'KIR', name: 'Kerry', city: 'Tralee', country: 'Ireland' },

  // France — domestic, regional, local
  { code: 'CDG', name: 'Paris Charles de Gaulle', city: 'Paris', country: 'France' },
  { code: 'ORY', name: 'Paris Orly', city: 'Paris', country: 'France' },
  { code: 'BVA', name: 'Paris Beauvais-Tillé', city: 'Paris', country: 'France' },
  { code: 'NCE', name: "Nice Côte d'Azur", city: 'Nice', country: 'France' },
  { code: 'MRS', name: 'Marseille Provence', city: 'Marseille', country: 'France' },
  { code: 'LYS', name: 'Lyon-Saint Exupéry', city: 'Lyon', country: 'France' },
  { code: 'TLS', name: 'Toulouse-Blagnac', city: 'Toulouse', country: 'France' },
  { code: 'BOD', name: 'Bordeaux-Mérignac', city: 'Bordeaux', country: 'France' },
  { code: 'NTE', name: 'Nantes Atlantique', city: 'Nantes', country: 'France' },
  { code: 'RNS', name: 'Rennes-Saint Jacques', city: 'Rennes', country: 'France' },
  { code: 'SXB', name: 'Strasbourg', city: 'Strasbourg', country: 'France' },
  { code: 'LIL', name: 'Lille', city: 'Lille', country: 'France' },
  { code: 'BES', name: 'Brest Bretagne', city: 'Brest', country: 'France' },
  { code: 'BIQ', name: 'Biarritz Pays Basque', city: 'Biarritz', country: 'France' },
  { code: 'PGF', name: 'Perpignan-Rivesaltes', city: 'Perpignan', country: 'France' },
  { code: 'MPL', name: 'Montpellier-Méditerranée', city: 'Montpellier', country: 'France' },
  { code: 'CFE', name: 'Clermont-Ferrand Auvergne', city: 'Clermont-Ferrand', country: 'France' },
  { code: 'LDE', name: 'Tarbes-Lourdes-Pyrénées', city: 'Tarbes', country: 'France' },
  { code: 'TLN', name: 'Toulon-Hyères', city: 'Toulon', country: 'France' },
  { code: 'AJA', name: 'Ajaccio Napoléon Bonaparte', city: 'Ajaccio', country: 'France' },
  { code: 'BIA', name: 'Bastia Poretta', city: 'Bastia', country: 'France' },
  { code: 'CLY', name: 'Calvi-Sainte-Catherine', city: 'Calvi', country: 'France' },
  { code: 'FSC', name: 'Figari Sud-Corse', city: 'Figari', country: 'France' },
  { code: 'FDF', name: 'Martinique Aimé Césaire International', city: 'Fort-de-France', country: 'France' },
  { code: 'PTP', name: 'Pointe-à-Pitre International', city: 'Pointe-à-Pitre', country: 'France' },
  { code: 'CAY', name: "Cayenne-Félix Eboué", city: 'Cayenne', country: 'France' },
  { code: 'RUN', name: 'Roland Garros', city: 'Saint-Denis (Réunion)', country: 'France' },
  // Germany — domestic, regional, local
  { code: 'FRA', name: 'Frankfurt', city: 'Frankfurt', country: 'Germany' },
  { code: 'HHN', name: 'Frankfurt-Hahn', city: 'Frankfurt', country: 'Germany' },
  { code: 'MUC', name: 'Munich', city: 'Munich', country: 'Germany' },
  { code: 'BER', name: 'Berlin Brandenburg', city: 'Berlin', country: 'Germany' },
  { code: 'HAM', name: 'Hamburg', city: 'Hamburg', country: 'Germany' },
  { code: 'DUS', name: 'Düsseldorf', city: 'Dusseldorf', country: 'Germany' },
  { code: 'CGN', name: 'Cologne Bonn', city: 'Cologne', country: 'Germany' },
  { code: 'STR', name: 'Stuttgart', city: 'Stuttgart', country: 'Germany' },
  { code: 'NUE', name: 'Nuremberg', city: 'Nuremberg', country: 'Germany' },
  { code: 'HAJ', name: 'Hannover-Langenhagen', city: 'Hanover', country: 'Germany' },
  { code: 'LEJ', name: 'Leipzig/Halle', city: 'Leipzig', country: 'Germany' },
  { code: 'DRS', name: 'Dresden', city: 'Dresden', country: 'Germany' },
  { code: 'BRE', name: 'Bremen', city: 'Bremen', country: 'Germany' },
  { code: 'DTM', name: 'Dortmund', city: 'Dortmund', country: 'Germany' },
  { code: 'PAD', name: 'Paderborn-Lippstadt', city: 'Paderborn', country: 'Germany' },
  { code: 'FMM', name: 'Memmingen', city: 'Memmingen', country: 'Germany' },
  { code: 'NRN', name: 'Weeze', city: 'Weeze', country: 'Germany' },
  { code: 'SCN', name: 'Saarbrücken', city: 'Saarbrücken', country: 'Germany' },
  { code: 'FKB', name: 'Karlsruhe/Baden-Baden', city: 'Baden-Baden', country: 'Germany' },
  { code: 'FDH', name: 'Friedrichshafen', city: 'Friedrichshafen', country: 'Germany' },
  { code: 'RLG', name: 'Rostock-Laage', city: 'Rostock', country: 'Germany' },
  { code: 'SXF', name: 'Berlin Schönefeld (legacy)', city: 'Berlin', country: 'Germany' },

  // Netherlands, Belgium, Luxembourg
  { code: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Netherlands' },
  { code: 'EIN', name: 'Eindhoven', city: 'Eindhoven', country: 'Netherlands' },
  { code: 'RTM', name: 'Rotterdam The Hague', city: 'Rotterdam', country: 'Netherlands' },
  { code: 'GRQ', name: 'Groningen Eelde', city: 'Groningen', country: 'Netherlands' },
  { code: 'MST', name: 'Maastricht Aachen', city: 'Maastricht', country: 'Netherlands' },
  { code: 'BRU', name: 'Brussels', city: 'Brussels', country: 'Belgium' },
  { code: 'CRL', name: 'Brussels South Charleroi', city: 'Charleroi', country: 'Belgium' },
  { code: 'ANR', name: 'Antwerp International', city: 'Antwerp', country: 'Belgium' },
  { code: 'LGG', name: 'Liège', city: 'Liège', country: 'Belgium' },
  { code: 'OST', name: 'Ostend-Bruges International', city: 'Ostend', country: 'Belgium' },
  { code: 'LUX', name: 'Luxembourg', city: 'Luxembourg', country: 'Luxembourg' },

  // Spain — domestic and regional
  { code: 'MAD', name: 'Adolfo Suárez Madrid-Barajas', city: 'Madrid', country: 'Spain' },
  { code: 'BCN', name: 'Barcelona-El Prat', city: 'Barcelona', country: 'Spain' },
  { code: 'AGP', name: 'Málaga-Costa del Sol', city: 'Malaga', country: 'Spain' },
  { code: 'PMI', name: 'Palma de Mallorca', city: 'Palma de Mallorca', country: 'Spain' },
  { code: 'IBZ', name: 'Ibiza', city: 'Ibiza', country: 'Spain' },
  { code: 'MAH', name: 'Menorca', city: 'Menorca', country: 'Spain' },
  { code: 'VLC', name: 'Valencia', city: 'Valencia', country: 'Spain' },
  { code: 'ALC', name: 'Alicante-Elche', city: 'Alicante', country: 'Spain' },
  { code: 'SVQ', name: 'Sevilla', city: 'Seville', country: 'Spain' },
  { code: 'BIO', name: 'Bilbao', city: 'Bilbao', country: 'Spain' },
  { code: 'OVD', name: 'Asturias', city: 'Oviedo', country: 'Spain' },
  { code: 'SCQ', name: 'Santiago de Compostela', city: 'Santiago de Compostela', country: 'Spain' },
  { code: 'VGO', name: 'Vigo-Peinador', city: 'Vigo', country: 'Spain' },
  { code: 'ZAZ', name: 'Zaragoza', city: 'Zaragoza', country: 'Spain' },
  { code: 'GRX', name: 'Federico García Lorca Granada-Jaén', city: 'Granada', country: 'Spain' },
  { code: 'XRY', name: 'Jerez', city: 'Jerez', country: 'Spain' },
  { code: 'LCG', name: 'A Coruña', city: 'A Coruña', country: 'Spain' },
  { code: 'TFN', name: 'Tenerife North-Ciudad de La Laguna', city: 'Tenerife', country: 'Spain' },
  { code: 'TFS', name: 'Tenerife South', city: 'Tenerife', country: 'Spain' },
  { code: 'LPA', name: 'Gran Canaria', city: 'Las Palmas', country: 'Spain' },
  { code: 'ACE', name: 'Lanzarote-César Manrique', city: 'Lanzarote', country: 'Spain' },
  { code: 'FUE', name: 'Fuerteventura', city: 'Fuerteventura', country: 'Spain' },
  { code: 'SPC', name: 'La Palma', city: 'La Palma', country: 'Spain' },

  // Portugal
  { code: 'LIS', name: 'Lisbon Humberto Delgado', city: 'Lisbon', country: 'Portugal' },
  { code: 'OPO', name: 'Porto', city: 'Porto', country: 'Portugal' },
  { code: 'FAO', name: 'Faro', city: 'Faro', country: 'Portugal' },
  { code: 'FNC', name: 'Madeira', city: 'Funchal', country: 'Portugal' },
  { code: 'PXO', name: 'Porto Santo', city: 'Porto Santo', country: 'Portugal' },
  { code: 'PDL', name: 'João Paulo II', city: 'Ponta Delgada', country: 'Portugal' },
  { code: 'TER', name: 'Lajes', city: 'Terceira', country: 'Portugal' },
  { code: 'HOR', name: 'Horta', city: 'Horta', country: 'Portugal' },

  // Italy — domestic and regional
  { code: 'FCO', name: 'Leonardo da Vinci-Fiumicino', city: 'Rome', country: 'Italy' },
  { code: 'CIA', name: 'Rome Ciampino', city: 'Rome', country: 'Italy' },
  { code: 'MXP', name: 'Milan Malpensa', city: 'Milan', country: 'Italy' },
  { code: 'LIN', name: 'Milan Linate', city: 'Milan', country: 'Italy' },
  { code: 'BGY', name: 'Milan Bergamo Orio al Serio', city: 'Bergamo', country: 'Italy' },
  { code: 'VCE', name: 'Venice Marco Polo', city: 'Venice', country: 'Italy' },
  { code: 'TSF', name: 'Treviso-Antonio Canova', city: 'Treviso', country: 'Italy' },
  { code: 'BLQ', name: 'Bologna Guglielmo Marconi', city: 'Bologna', country: 'Italy' },
  { code: 'NAP', name: 'Naples International', city: 'Naples', country: 'Italy' },
  { code: 'CTA', name: 'Catania-Fontanarossa', city: 'Catania', country: 'Italy' },
  { code: 'PMO', name: 'Palermo Falcone-Borsellino', city: 'Palermo', country: 'Italy' },
  { code: 'BRI', name: 'Bari Karol Wojtyła', city: 'Bari', country: 'Italy' },
  { code: 'BDS', name: 'Brindisi-Casale', city: 'Brindisi', country: 'Italy' },
  { code: 'CAG', name: 'Cagliari-Elmas', city: 'Cagliari', country: 'Italy' },
  { code: 'OLB', name: 'Olbia Costa Smeralda', city: 'Olbia', country: 'Italy' },
  { code: 'AHO', name: 'Alghero-Fertilia', city: 'Alghero', country: 'Italy' },
  { code: 'TRN', name: 'Turin', city: 'Turin', country: 'Italy' },
  { code: 'GOA', name: 'Genoa Cristoforo Colombo', city: 'Genoa', country: 'Italy' },
  { code: 'PSA', name: 'Pisa International', city: 'Pisa', country: 'Italy' },
  { code: 'FLR', name: 'Florence Peretola', city: 'Florence', country: 'Italy' },
  { code: 'VRN', name: 'Verona Villafranca', city: 'Verona', country: 'Italy' },
  { code: 'TRS', name: 'Trieste-Friuli Venezia Giulia', city: 'Trieste', country: 'Italy' },
  { code: 'AOI', name: 'Ancona Falconara', city: 'Ancona', country: 'Italy' },
  { code: 'PEG', name: 'Perugia San Francesco', city: 'Perugia', country: 'Italy' },
  { code: 'PSR', name: 'Pescara', city: 'Pescara', country: 'Italy' },
  { code: 'REG', name: 'Reggio Calabria', city: 'Reggio Calabria', country: 'Italy' },
  { code: 'LMP', name: 'Lampedusa', city: 'Lampedusa', country: 'Italy' },
  { code: 'PNL', name: 'Pantelleria', city: 'Pantelleria', country: 'Italy' },

  // Switzerland & Austria
  { code: 'ZRH', name: 'Zurich', city: 'Zurich', country: 'Switzerland' },
  { code: 'GVA', name: 'Geneva', city: 'Geneva', country: 'Switzerland' },
  { code: 'BSL', name: 'EuroAirport Basel-Mulhouse-Freiburg', city: 'Basel', country: 'Switzerland' },
  { code: 'BRN', name: 'Bern', city: 'Bern', country: 'Switzerland' },
  { code: 'LUG', name: 'Lugano', city: 'Lugano', country: 'Switzerland' },
  { code: 'SIR', name: 'Sion', city: 'Sion', country: 'Switzerland' },
  { code: 'VIE', name: 'Vienna International', city: 'Vienna', country: 'Austria' },
  { code: 'INN', name: 'Innsbruck', city: 'Innsbruck', country: 'Austria' },
  { code: 'SZG', name: 'Salzburg W. A. Mozart', city: 'Salzburg', country: 'Austria' },
  { code: 'GRZ', name: 'Graz', city: 'Graz', country: 'Austria' },
  { code: 'LNZ', name: 'Linz Hörsching', city: 'Linz', country: 'Austria' },
  { code: 'KLU', name: 'Klagenfurt', city: 'Klagenfurt', country: 'Austria' },

  // Nordics — domestic & regional
  { code: 'CPH', name: 'Copenhagen', city: 'Copenhagen', country: 'Denmark' },
  { code: 'AAL', name: 'Aalborg', city: 'Aalborg', country: 'Denmark' },
  { code: 'AAR', name: 'Aarhus', city: 'Aarhus', country: 'Denmark' },
  { code: 'BLL', name: 'Billund', city: 'Billund', country: 'Denmark' },
  { code: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norway' },
  { code: 'TRF', name: 'Sandefjord Torp', city: 'Oslo', country: 'Norway' },
  { code: 'BGO', name: 'Bergen Flesland', city: 'Bergen', country: 'Norway' },
  { code: 'TRD', name: 'Trondheim Værnes', city: 'Trondheim', country: 'Norway' },
  { code: 'SVG', name: 'Stavanger Sola', city: 'Stavanger', country: 'Norway' },
  { code: 'TOS', name: 'Tromsø', city: 'Tromsø', country: 'Norway' },
  { code: 'BOO', name: 'Bodø', city: 'Bodø', country: 'Norway' },
  { code: 'KRS', name: 'Kristiansand Kjevik', city: 'Kristiansand', country: 'Norway' },
  { code: 'AES', name: 'Ålesund Vigra', city: 'Ålesund', country: 'Norway' },
  { code: 'LYR', name: 'Svalbard', city: 'Longyearbyen', country: 'Norway' },
  { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stockholm', country: 'Sweden' },
  { code: 'BMA', name: 'Stockholm Bromma', city: 'Stockholm', country: 'Sweden' },
  { code: 'NYO', name: 'Stockholm Skavsta', city: 'Stockholm', country: 'Sweden' },
  { code: 'GOT', name: 'Göteborg Landvetter', city: 'Gothenburg', country: 'Sweden' },
  { code: 'MMX', name: 'Malmö', city: 'Malmö', country: 'Sweden' },
  { code: 'LLA', name: 'Luleå', city: 'Luleå', country: 'Sweden' },
  { code: 'UME', name: 'Umeå', city: 'Umeå', country: 'Sweden' },
  { code: 'VBY', name: 'Visby', city: 'Visby', country: 'Sweden' },
  { code: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki', country: 'Finland' },
  { code: 'TMP', name: 'Tampere-Pirkkala', city: 'Tampere', country: 'Finland' },
  { code: 'TKU', name: 'Turku', city: 'Turku', country: 'Finland' },
  { code: 'OUL', name: 'Oulu', city: 'Oulu', country: 'Finland' },
  { code: 'RVN', name: 'Rovaniemi', city: 'Rovaniemi', country: 'Finland' },
  { code: 'KEF', name: 'Keflavík International', city: 'Reykjavík', country: 'Iceland' },
  { code: 'RKV', name: 'Reykjavík Domestic', city: 'Reykjavík', country: 'Iceland' },
  { code: 'AEY', name: 'Akureyri', city: 'Akureyri', country: 'Iceland' },

  // Greece — islands and regional
  { code: 'ATH', name: 'Athens International', city: 'Athens', country: 'Greece' },
  { code: 'SKG', name: 'Thessaloniki Macedonia', city: 'Thessaloniki', country: 'Greece' },
  { code: 'HER', name: 'Heraklion Nikos Kazantzakis', city: 'Heraklion', country: 'Greece' },
  { code: 'CHQ', name: 'Chania', city: 'Chania', country: 'Greece' },
  { code: 'RHO', name: 'Rhodes', city: 'Rhodes', country: 'Greece' },
  { code: 'KGS', name: 'Hippocrates International', city: 'Kos', country: 'Greece' },
  { code: 'JTR', name: 'Santorini', city: 'Santorini', country: 'Greece' },
  { code: 'JMK', name: 'Mykonos', city: 'Mykonos', country: 'Greece' },
  { code: 'CFU', name: 'Corfu', city: 'Corfu', country: 'Greece' },
  { code: 'ZTH', name: 'Zakynthos', city: 'Zakynthos', country: 'Greece' },
  { code: 'KLX', name: 'Kalamata', city: 'Kalamata', country: 'Greece' },

  // Turkey — domestic and regional
  { code: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turkey' },
  { code: 'SAW', name: 'Istanbul Sabiha Gökçen', city: 'Istanbul', country: 'Turkey' },
  { code: 'ESB', name: 'Ankara Esenboğa', city: 'Ankara', country: 'Turkey' },
  { code: 'ADB', name: 'İzmir Adnan Menderes', city: 'Izmir', country: 'Turkey' },
  { code: 'AYT', name: 'Antalya', city: 'Antalya', country: 'Turkey' },
  { code: 'BJV', name: 'Milas-Bodrum', city: 'Bodrum', country: 'Turkey' },
  { code: 'DLM', name: 'Dalaman', city: 'Dalaman', country: 'Turkey' },
  { code: 'TZX', name: 'Trabzon', city: 'Trabzon', country: 'Turkey' },
  { code: 'ADA', name: 'Adana Şakirpaşa', city: 'Adana', country: 'Turkey' },
  { code: 'GZT', name: 'Gaziantep', city: 'Gaziantep', country: 'Turkey' },
  { code: 'ASR', name: 'Kayseri Erkilet', city: 'Kayseri', country: 'Turkey' },
  { code: 'KYA', name: 'Konya', city: 'Konya', country: 'Turkey' },

  // Eastern Europe — domestic and regional
  { code: 'WAW', name: 'Warsaw Chopin', city: 'Warsaw', country: 'Poland' },
  { code: 'WMI', name: 'Warsaw-Modlin', city: 'Warsaw', country: 'Poland' },
  { code: 'KRK', name: 'Kraków John Paul II', city: 'Kraków', country: 'Poland' },
  { code: 'GDN', name: 'Gdańsk Lech Wałęsa', city: 'Gdańsk', country: 'Poland' },
  { code: 'WRO', name: 'Wrocław Copernicus', city: 'Wrocław', country: 'Poland' },
  { code: 'POZ', name: 'Poznań-Ławica', city: 'Poznań', country: 'Poland' },
  { code: 'KTW', name: 'Katowice', city: 'Katowice', country: 'Poland' },
  { code: 'RZE', name: 'Rzeszów-Jasionka', city: 'Rzeszów', country: 'Poland' },
  { code: 'PRG', name: 'Václav Havel Prague', city: 'Prague', country: 'Czech Republic' },
  { code: 'BRQ', name: 'Brno-Tuřany', city: 'Brno', country: 'Czech Republic' },
  { code: 'OSR', name: 'Leoš Janáček Ostrava', city: 'Ostrava', country: 'Czech Republic' },
  { code: 'BTS', name: 'M. R. Štefánik', city: 'Bratislava', country: 'Slovakia' },
  { code: 'KSC', name: 'Košice', city: 'Košice', country: 'Slovakia' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt', city: 'Budapest', country: 'Hungary' },
  { code: 'DEB', name: 'Debrecen', city: 'Debrecen', country: 'Hungary' },
  { code: 'OTP', name: 'Henri Coandă International', city: 'Bucharest', country: 'Romania' },
  { code: 'CLJ', name: 'Cluj-Napoca International', city: 'Cluj-Napoca', country: 'Romania' },
  { code: 'TSR', name: 'Timișoara Traian Vuia', city: 'Timișoara', country: 'Romania' },
  { code: 'IAS', name: 'Iași', city: 'Iași', country: 'Romania' },
  { code: 'SOF', name: 'Sofia', city: 'Sofia', country: 'Bulgaria' },
  { code: 'PDV', name: 'Plovdiv', city: 'Plovdiv', country: 'Bulgaria' },
  { code: 'VAR', name: 'Varna', city: 'Varna', country: 'Bulgaria' },
  { code: 'BOJ', name: 'Burgas', city: 'Burgas', country: 'Bulgaria' },
  { code: 'BEG', name: 'Belgrade Nikola Tesla', city: 'Belgrade', country: 'Serbia' },
  { code: 'ZAG', name: 'Zagreb Franjo Tuđman', city: 'Zagreb', country: 'Croatia' },
  { code: 'SPU', name: 'Split', city: 'Split', country: 'Croatia' },
  { code: 'DBV', name: 'Dubrovnik', city: 'Dubrovnik', country: 'Croatia' },
  { code: 'ZAD', name: 'Zadar', city: 'Zadar', country: 'Croatia' },
  { code: 'PUY', name: 'Pula', city: 'Pula', country: 'Croatia' },
  { code: 'LJU', name: 'Ljubljana Jože Pučnik', city: 'Ljubljana', country: 'Slovenia' },
  { code: 'SJJ', name: 'Sarajevo', city: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { code: 'TIV', name: 'Tivat', city: 'Tivat', country: 'Montenegro' },
  { code: 'TGD', name: 'Podgorica', city: 'Podgorica', country: 'Montenegro' },
  { code: 'SKP', name: 'Skopje', city: 'Skopje', country: 'North Macedonia' },
  { code: 'TIA', name: 'Tirana', city: 'Tirana', country: 'Albania' },
  { code: 'KIV', name: 'Chișinău', city: 'Chișinău', country: 'Moldova' },
  { code: 'KBP', name: 'Kyiv Boryspil', city: 'Kyiv', country: 'Ukraine' },
  { code: 'IEV', name: 'Kyiv Zhuliany', city: 'Kyiv', country: 'Ukraine' },
  { code: 'LWO', name: 'Lviv', city: 'Lviv', country: 'Ukraine' },
  { code: 'ODS', name: 'Odesa', city: 'Odesa', country: 'Ukraine' },
  { code: 'MSQ', name: 'Minsk National', city: 'Minsk', country: 'Belarus' },
  { code: 'RIX', name: 'Riga', city: 'Riga', country: 'Latvia' },
  { code: 'TLL', name: 'Tallinn Lennart Meri', city: 'Tallinn', country: 'Estonia' },
  { code: 'VNO', name: 'Vilnius', city: 'Vilnius', country: 'Lithuania' },
  { code: 'KUN', name: 'Kaunas', city: 'Kaunas', country: 'Lithuania' },

  // Russia & former Soviet states — domestic and regional
  { code: 'SVO', name: 'Sheremetyevo International', city: 'Moscow', country: 'Russia' },
  { code: 'DME', name: 'Domodedovo International', city: 'Moscow', country: 'Russia' },
  { code: 'VKO', name: 'Vnukovo International', city: 'Moscow', country: 'Russia' },
  { code: 'ZIA', name: 'Zhukovsky International', city: 'Moscow', country: 'Russia' },
  { code: 'LED', name: 'Pulkovo', city: 'Saint Petersburg', country: 'Russia' },
  { code: 'KZN', name: 'Kazan International', city: 'Kazan', country: 'Russia' },
  { code: 'AER', name: 'Sochi International', city: 'Sochi', country: 'Russia' },
  { code: 'KRR', name: 'Krasnodar International', city: 'Krasnodar', country: 'Russia' },
  { code: 'ROV', name: 'Platov International', city: 'Rostov-on-Don', country: 'Russia' },
  { code: 'SVX', name: 'Koltsovo International', city: 'Yekaterinburg', country: 'Russia' },
  { code: 'OVB', name: 'Tolmachevo', city: 'Novosibirsk', country: 'Russia' },
  { code: 'KJA', name: 'Yemelyanovo', city: 'Krasnoyarsk', country: 'Russia' },
  { code: 'IKT', name: 'Irkutsk International', city: 'Irkutsk', country: 'Russia' },
  { code: 'VVO', name: 'Vladivostok International', city: 'Vladivostok', country: 'Russia' },
  { code: 'KHV', name: 'Khabarovsk Novy', city: 'Khabarovsk', country: 'Russia' },
  { code: 'PKC', name: 'Yelizovo', city: 'Petropavlovsk-Kamchatsky', country: 'Russia' },
  { code: 'ALA', name: 'Almaty International', city: 'Almaty', country: 'Kazakhstan' },
  { code: 'NQZ', name: 'Nursultan Nazarbayev International', city: 'Astana', country: 'Kazakhstan' },
  { code: 'TAS', name: 'Tashkent International', city: 'Tashkent', country: 'Uzbekistan' },
  { code: 'SKD', name: 'Samarkand', city: 'Samarkand', country: 'Uzbekistan' },
  { code: 'FRU', name: 'Manas International', city: 'Bishkek', country: 'Kyrgyzstan' },
  { code: 'DYU', name: 'Dushanbe International', city: 'Dushanbe', country: 'Tajikistan' },
  { code: 'ASB', name: 'Ashgabat', city: 'Ashgabat', country: 'Turkmenistan' },
  { code: 'GYD', name: 'Heydar Aliyev International', city: 'Baku', country: 'Azerbaijan' },
  { code: 'TBS', name: 'Tbilisi International', city: 'Tbilisi', country: 'Georgia' },
  { code: 'BUS', name: 'Batumi', city: 'Batumi', country: 'Georgia' },
  { code: 'EVN', name: 'Zvartnots International', city: 'Yerevan', country: 'Armenia' },
  // Middle East — domestic and regional
  { code: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'United Arab Emirates' },
  { code: 'DWC', name: 'Al Maktoum International', city: 'Dubai', country: 'United Arab Emirates' },
  { code: 'AUH', name: 'Abu Dhabi International', city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { code: 'SHJ', name: 'Sharjah International', city: 'Sharjah', country: 'United Arab Emirates' },
  { code: 'RKT', name: 'Ras Al Khaimah International', city: 'Ras Al Khaimah', country: 'United Arab Emirates' },
  { code: 'AAN', name: 'Al Ain International', city: 'Al Ain', country: 'United Arab Emirates' },
  { code: 'FJR', name: 'Fujairah International', city: 'Fujairah', country: 'United Arab Emirates' },
  { code: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Qatar' },
  { code: 'RUH', name: 'King Khalid International', city: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'JED', name: 'King Abdulaziz International', city: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'DMM', name: 'King Fahd International', city: 'Dammam', country: 'Saudi Arabia' },
  { code: 'MED', name: 'Prince Mohammad Bin Abdulaziz', city: 'Medina', country: 'Saudi Arabia' },
  { code: 'AHB', name: 'Abha International', city: 'Abha', country: 'Saudi Arabia' },
  { code: 'TUU', name: 'Tabuk Regional', city: 'Tabuk', country: 'Saudi Arabia' },
  { code: 'YNB', name: 'Yanbu', city: 'Yanbu', country: 'Saudi Arabia' },
  { code: 'BAH', name: 'Bahrain International', city: 'Manama', country: 'Bahrain' },
  { code: 'MCT', name: 'Muscat International', city: 'Muscat', country: 'Oman' },
  { code: 'SLL', name: 'Salalah', city: 'Salalah', country: 'Oman' },
  { code: 'KHS', name: 'Khasab', city: 'Khasab', country: 'Oman' },
  { code: 'AMM', name: 'Queen Alia International', city: 'Amman', country: 'Jordan' },
  { code: 'AQJ', name: 'King Hussein International', city: 'Aqaba', country: 'Jordan' },
  { code: 'TLV', name: 'Ben Gurion', city: 'Tel Aviv', country: 'Israel' },
  { code: 'ETM', name: 'Ramon', city: 'Eilat', country: 'Israel' },
  { code: 'HFA', name: 'Haifa', city: 'Haifa', country: 'Israel' },
  { code: 'KWI', name: 'Kuwait International', city: 'Kuwait City', country: 'Kuwait' },
  { code: 'BEY', name: 'Beirut-Rafic Hariri International', city: 'Beirut', country: 'Lebanon' },
  { code: 'BGW', name: 'Baghdad International', city: 'Baghdad', country: 'Iraq' },
  { code: 'EBL', name: 'Erbil International', city: 'Erbil', country: 'Iraq' },
  { code: 'BSR', name: 'Basra International', city: 'Basra', country: 'Iraq' },
  { code: 'NJF', name: 'Al Najaf International', city: 'Najaf', country: 'Iraq' },
  { code: 'ISU', name: 'Sulaymaniyah International', city: 'Sulaymaniyah', country: 'Iraq' },
  { code: 'IKA', name: 'Tehran Imam Khomeini International', city: 'Tehran', country: 'Iran' },
  { code: 'THR', name: 'Mehrabad International', city: 'Tehran', country: 'Iran' },
  { code: 'MHD', name: 'Mashhad International', city: 'Mashhad', country: 'Iran' },
  { code: 'IFN', name: 'Isfahan International', city: 'Isfahan', country: 'Iran' },
  { code: 'SYZ', name: 'Shiraz International', city: 'Shiraz', country: 'Iran' },
  // Singapore, Hong Kong, Macau, Taiwan
  { code: 'SIN', name: 'Singapore Changi', city: 'Singapore', country: 'Singapore' },
  { code: 'XSP', name: 'Seletar', city: 'Singapore', country: 'Singapore' },
  { code: 'HKG', name: 'Hong Kong International', city: 'Hong Kong', country: 'Hong Kong' },
  { code: 'MFM', name: 'Macau International', city: 'Macau', country: 'Macau' },
  { code: 'TPE', name: 'Taiwan Taoyuan International', city: 'Taipei', country: 'Taiwan' },
  { code: 'TSA', name: 'Taipei Songshan', city: 'Taipei', country: 'Taiwan' },
  { code: 'KHH', name: 'Kaohsiung International', city: 'Kaohsiung', country: 'Taiwan' },
  { code: 'RMQ', name: 'Taichung', city: 'Taichung', country: 'Taiwan' },
  { code: 'TNN', name: 'Tainan', city: 'Tainan', country: 'Taiwan' },
  { code: 'HUN', name: 'Hualien', city: 'Hualien', country: 'Taiwan' },
  { code: 'MZG', name: 'Magong', city: 'Penghu', country: 'Taiwan' },

  // Japan — domestic and regional
  { code: 'NRT', name: 'Narita International', city: 'Tokyo', country: 'Japan' },
  { code: 'HND', name: 'Haneda', city: 'Tokyo', country: 'Japan' },
  { code: 'KIX', name: 'Kansai International', city: 'Osaka', country: 'Japan' },
  { code: 'ITM', name: 'Osaka Itami', city: 'Osaka', country: 'Japan' },
  { code: 'UKB', name: 'Kobe', city: 'Kobe', country: 'Japan' },
  { code: 'NGO', name: 'Chubu Centrair International', city: 'Nagoya', country: 'Japan' },
  { code: 'NKM', name: 'Nagoya Komaki', city: 'Nagoya', country: 'Japan' },
  { code: 'CTS', name: 'New Chitose', city: 'Sapporo', country: 'Japan' },
  { code: 'OKD', name: 'Okadama', city: 'Sapporo', country: 'Japan' },
  { code: 'HKD', name: 'Hakodate', city: 'Hakodate', country: 'Japan' },
  { code: 'AOJ', name: 'Aomori', city: 'Aomori', country: 'Japan' },
  { code: 'AKJ', name: 'Asahikawa', city: 'Asahikawa', country: 'Japan' },
  { code: 'KUH', name: 'Kushiro', city: 'Kushiro', country: 'Japan' },
  { code: 'SDJ', name: 'Sendai', city: 'Sendai', country: 'Japan' },
  { code: 'KIJ', name: 'Niigata', city: 'Niigata', country: 'Japan' },
  { code: 'TOY', name: 'Toyama', city: 'Toyama', country: 'Japan' },
  { code: 'KMQ', name: 'Komatsu', city: 'Kanazawa', country: 'Japan' },
  { code: 'FSZ', name: 'Mt. Fuji Shizuoka', city: 'Shizuoka', country: 'Japan' },
  { code: 'HIJ', name: 'Hiroshima', city: 'Hiroshima', country: 'Japan' },
  { code: 'OKJ', name: 'Okayama', city: 'Okayama', country: 'Japan' },
  { code: 'TAK', name: 'Takamatsu', city: 'Takamatsu', country: 'Japan' },
  { code: 'MYJ', name: 'Matsuyama', city: 'Matsuyama', country: 'Japan' },
  { code: 'KCZ', name: 'Kōchi Ryōma', city: 'Kōchi', country: 'Japan' },
  { code: 'FUK', name: 'Fukuoka', city: 'Fukuoka', country: 'Japan' },
  { code: 'KMJ', name: 'Kumamoto', city: 'Kumamoto', country: 'Japan' },
  { code: 'NGS', name: 'Nagasaki', city: 'Nagasaki', country: 'Japan' },
  { code: 'OIT', name: 'Ōita', city: 'Ōita', country: 'Japan' },
  { code: 'KMI', name: 'Miyazaki', city: 'Miyazaki', country: 'Japan' },
  { code: 'KOJ', name: 'Kagoshima', city: 'Kagoshima', country: 'Japan' },
  { code: 'OKA', name: 'Naha', city: 'Okinawa', country: 'Japan' },
  { code: 'ISG', name: 'Ishigaki', city: 'Ishigaki', country: 'Japan' },
  { code: 'MMY', name: 'Miyako', city: 'Miyakojima', country: 'Japan' },

  // South Korea — domestic and regional
  { code: 'ICN', name: 'Incheon International', city: 'Seoul', country: 'South Korea' },
  { code: 'GMP', name: 'Gimpo International', city: 'Seoul', country: 'South Korea' },
  { code: 'PUS', name: 'Gimhae International', city: 'Busan', country: 'South Korea' },
  { code: 'CJU', name: 'Jeju International', city: 'Jeju', country: 'South Korea' },
  { code: 'TAE', name: 'Daegu International', city: 'Daegu', country: 'South Korea' },
  { code: 'CJJ', name: 'Cheongju International', city: 'Cheongju', country: 'South Korea' },
  { code: 'KWJ', name: 'Gwangju', city: 'Gwangju', country: 'South Korea' },
  { code: 'USN', name: 'Ulsan', city: 'Ulsan', country: 'South Korea' },
  { code: 'MPK', name: 'Mokpo', city: 'Mokpo', country: 'South Korea' },
  { code: 'YNY', name: 'Yangyang International', city: 'Yangyang', country: 'South Korea' },

  // China — domestic and regional
  { code: 'PEK', name: 'Beijing Capital International', city: 'Beijing', country: 'China' },
  { code: 'PKX', name: 'Beijing Daxing International', city: 'Beijing', country: 'China' },
  { code: 'PVG', name: 'Shanghai Pudong International', city: 'Shanghai', country: 'China' },
  { code: 'SHA', name: 'Shanghai Hongqiao International', city: 'Shanghai', country: 'China' },
  { code: 'CAN', name: 'Guangzhou Baiyun International', city: 'Guangzhou', country: 'China' },
  { code: 'SZX', name: "Shenzhen Bao'an International", city: 'Shenzhen', country: 'China' },
  { code: 'CTU', name: 'Chengdu Shuangliu International', city: 'Chengdu', country: 'China' },
  { code: 'TFU', name: 'Chengdu Tianfu International', city: 'Chengdu', country: 'China' },
  { code: 'CKG', name: 'Chongqing Jiangbei International', city: 'Chongqing', country: 'China' },
  { code: 'XIY', name: "Xi'an Xianyang International", city: "Xi'an", country: 'China' },
  { code: 'KMG', name: 'Kunming Changshui International', city: 'Kunming', country: 'China' },
  { code: 'HGH', name: 'Hangzhou Xiaoshan International', city: 'Hangzhou', country: 'China' },
  { code: 'NKG', name: 'Nanjing Lukou International', city: 'Nanjing', country: 'China' },
  { code: 'WUH', name: 'Wuhan Tianhe International', city: 'Wuhan', country: 'China' },
  { code: 'XMN', name: 'Xiamen Gaoqi International', city: 'Xiamen', country: 'China' },
  { code: 'TAO', name: 'Qingdao Jiaodong International', city: 'Qingdao', country: 'China' },
  { code: 'TSN', name: 'Tianjin Binhai International', city: 'Tianjin', country: 'China' },
  { code: 'DLC', name: 'Dalian Zhoushuizi International', city: 'Dalian', country: 'China' },
  { code: 'SHE', name: 'Shenyang Taoxian International', city: 'Shenyang', country: 'China' },
  { code: 'HRB', name: 'Harbin Taiping International', city: 'Harbin', country: 'China' },
  { code: 'CGO', name: 'Zhengzhou Xinzheng International', city: 'Zhengzhou', country: 'China' },
  { code: 'CSX', name: 'Changsha Huanghua International', city: 'Changsha', country: 'China' },
  { code: 'KWE', name: 'Guiyang Longdongbao International', city: 'Guiyang', country: 'China' },
  { code: 'NNG', name: 'Nanning Wuxu International', city: 'Nanning', country: 'China' },
  { code: 'HAK', name: 'Haikou Meilan International', city: 'Haikou', country: 'China' },
  { code: 'SYX', name: 'Sanya Phoenix International', city: 'Sanya', country: 'China' },
  { code: 'LHW', name: 'Lanzhou Zhongchuan International', city: 'Lanzhou', country: 'China' },
  { code: 'URC', name: 'Ürümqi Diwopu International', city: 'Ürümqi', country: 'China' },
  { code: 'LXA', name: 'Lhasa Gonggar', city: 'Lhasa', country: 'China' },
  { code: 'YNT', name: 'Yantai Penglai International', city: 'Yantai', country: 'China' },
  { code: 'TYN', name: 'Taiyuan Wusu International', city: 'Taiyuan', country: 'China' },
  { code: 'HFE', name: 'Hefei Xinqiao International', city: 'Hefei', country: 'China' },
  { code: 'KHN', name: 'Nanchang Changbei International', city: 'Nanchang', country: 'China' },
  { code: 'FOC', name: 'Fuzhou Changle International', city: 'Fuzhou', country: 'China' },

  // Mongolia
  { code: 'UBN', name: 'Chinggis Khaan International', city: 'Ulaanbaatar', country: 'Mongolia' },

  // Thailand — domestic and regional
  { code: 'BKK', name: 'Suvarnabhumi', city: 'Bangkok', country: 'Thailand' },
  { code: 'DMK', name: 'Don Mueang International', city: 'Bangkok', country: 'Thailand' },
  { code: 'CNX', name: 'Chiang Mai International', city: 'Chiang Mai', country: 'Thailand' },
  { code: 'CEI', name: 'Chiang Rai International', city: 'Chiang Rai', country: 'Thailand' },
  { code: 'HKT', name: 'Phuket International', city: 'Phuket', country: 'Thailand' },
  { code: 'USM', name: 'Samui', city: 'Koh Samui', country: 'Thailand' },
  { code: 'KBV', name: 'Krabi', city: 'Krabi', country: 'Thailand' },
  { code: 'HDY', name: 'Hat Yai International', city: 'Hat Yai', country: 'Thailand' },
  { code: 'UTP', name: 'U-Tapao Rayong-Pattaya International', city: 'Pattaya', country: 'Thailand' },
  { code: 'UBP', name: 'Ubon Ratchathani', city: 'Ubon Ratchathani', country: 'Thailand' },
  { code: 'KKC', name: 'Khon Kaen', city: 'Khon Kaen', country: 'Thailand' },
  { code: 'TDX', name: 'Trat', city: 'Trat', country: 'Thailand' },

  // Malaysia & Brunei
  { code: 'KUL', name: 'Kuala Lumpur International', city: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'SZB', name: 'Sultan Abdul Aziz Shah', city: 'Subang', country: 'Malaysia' },
  { code: 'PEN', name: 'Penang International', city: 'Penang', country: 'Malaysia' },
  { code: 'LGK', name: 'Langkawi International', city: 'Langkawi', country: 'Malaysia' },
  { code: 'BKI', name: 'Kota Kinabalu International', city: 'Kota Kinabalu', country: 'Malaysia' },
  { code: 'KCH', name: 'Kuching International', city: 'Kuching', country: 'Malaysia' },
  { code: 'JHB', name: 'Senai International', city: 'Johor Bahru', country: 'Malaysia' },
  { code: 'KBR', name: 'Sultan Ismail Petra', city: 'Kota Bharu', country: 'Malaysia' },
  { code: 'KTE', name: 'Kerteh', city: 'Kerteh', country: 'Malaysia' },
  { code: 'TWU', name: 'Tawau', city: 'Tawau', country: 'Malaysia' },
  { code: 'SDK', name: 'Sandakan', city: 'Sandakan', country: 'Malaysia' },
  { code: 'MYY', name: 'Miri', city: 'Miri', country: 'Malaysia' },
  { code: 'BWN', name: 'Brunei International', city: 'Bandar Seri Begawan', country: 'Brunei' },

  // Indonesia — domestic and regional
  { code: 'CGK', name: 'Soekarno-Hatta International', city: 'Jakarta', country: 'Indonesia' },
  { code: 'HLP', name: 'Halim Perdanakusuma International', city: 'Jakarta', country: 'Indonesia' },
  { code: 'DPS', name: 'Ngurah Rai International', city: 'Denpasar', country: 'Indonesia' },
  { code: 'SUB', name: 'Juanda International', city: 'Surabaya', country: 'Indonesia' },
  { code: 'KNO', name: 'Kualanamu International', city: 'Medan', country: 'Indonesia' },
  { code: 'UPG', name: 'Sultan Hasanuddin International', city: 'Makassar', country: 'Indonesia' },
  { code: 'BPN', name: 'Sultan Aji Muhammad Sulaiman Sepinggan International', city: 'Balikpapan', country: 'Indonesia' },
  { code: 'JOG', name: 'Adisutjipto International', city: 'Yogyakarta', country: 'Indonesia' },
  { code: 'YIA', name: 'Yogyakarta International', city: 'Yogyakarta', country: 'Indonesia' },
  { code: 'SOC', name: 'Adisumarmo International', city: 'Surakarta', country: 'Indonesia' },
  { code: 'SRG', name: 'Ahmad Yani International', city: 'Semarang', country: 'Indonesia' },
  { code: 'BDO', name: 'Husein Sastranegara International', city: 'Bandung', country: 'Indonesia' },
  { code: 'PLM', name: 'Sultan Mahmud Badaruddin II International', city: 'Palembang', country: 'Indonesia' },
  { code: 'PKU', name: 'Sultan Syarif Kasim II International', city: 'Pekanbaru', country: 'Indonesia' },
  { code: 'PNK', name: 'Supadio International', city: 'Pontianak', country: 'Indonesia' },
  { code: 'AMQ', name: 'Pattimura', city: 'Ambon', country: 'Indonesia' },
  { code: 'DJJ', name: 'Sentani International', city: 'Jayapura', country: 'Indonesia' },
  { code: 'LOP', name: 'Lombok International', city: 'Lombok', country: 'Indonesia' },
  { code: 'KOE', name: 'El Tari', city: 'Kupang', country: 'Indonesia' },
  { code: 'BTH', name: 'Hang Nadim International', city: 'Batam', country: 'Indonesia' },

  // Philippines — domestic and regional
  { code: 'MNL', name: 'Ninoy Aquino International', city: 'Manila', country: 'Philippines' },
  { code: 'CRK', name: 'Clark International', city: 'Angeles City', country: 'Philippines' },
  { code: 'CEB', name: 'Mactan-Cebu International', city: 'Cebu', country: 'Philippines' },
  { code: 'DVO', name: 'Francisco Bangoy International', city: 'Davao', country: 'Philippines' },
  { code: 'ILO', name: 'Iloilo International', city: 'Iloilo', country: 'Philippines' },
  { code: 'PPS', name: 'Puerto Princesa International', city: 'Puerto Princesa', country: 'Philippines' },
  { code: 'KLO', name: 'Kalibo International', city: 'Kalibo', country: 'Philippines' },
  { code: 'MPH', name: 'Godofredo P. Ramos', city: 'Caticlan', country: 'Philippines' },
  { code: 'TAG', name: 'Bohol-Panglao International', city: 'Tagbilaran', country: 'Philippines' },
  { code: 'ZAM', name: 'Zamboanga International', city: 'Zamboanga', country: 'Philippines' },
  { code: 'CGY', name: 'Cagayan de Oro Laguindingan', city: 'Cagayan de Oro', country: 'Philippines' },
  { code: 'BCD', name: 'Bacolod-Silay International', city: 'Bacolod', country: 'Philippines' },
  { code: 'GES', name: 'General Santos International', city: 'General Santos', country: 'Philippines' },

  // Vietnam — domestic and regional
  { code: 'SGN', name: 'Tan Son Nhat International', city: 'Ho Chi Minh City', country: 'Vietnam' },
  { code: 'HAN', name: 'Noi Bai International', city: 'Hanoi', country: 'Vietnam' },
  { code: 'DAD', name: 'Da Nang International', city: 'Da Nang', country: 'Vietnam' },
  { code: 'CXR', name: 'Cam Ranh International', city: 'Nha Trang', country: 'Vietnam' },
  { code: 'PQC', name: 'Phu Quoc International', city: 'Phu Quoc', country: 'Vietnam' },
  { code: 'HPH', name: 'Cat Bi International', city: 'Hai Phong', country: 'Vietnam' },
  { code: 'HUI', name: 'Phu Bai International', city: 'Hue', country: 'Vietnam' },
  { code: 'DLI', name: 'Lien Khuong', city: 'Da Lat', country: 'Vietnam' },
  { code: 'VCA', name: 'Can Tho International', city: 'Can Tho', country: 'Vietnam' },
  { code: 'VII', name: 'Vinh', city: 'Vinh', country: 'Vietnam' },

  // Cambodia, Laos, Myanmar
  { code: 'PNH', name: 'Phnom Penh International', city: 'Phnom Penh', country: 'Cambodia' },
  { code: 'REP', name: 'Siem Reap-Angkor International', city: 'Siem Reap', country: 'Cambodia' },
  { code: 'KOS', name: 'Sihanoukville International', city: 'Sihanoukville', country: 'Cambodia' },
  { code: 'VTE', name: 'Wattay International', city: 'Vientiane', country: 'Laos' },
  { code: 'LPQ', name: 'Luang Prabang International', city: 'Luang Prabang', country: 'Laos' },
  { code: 'PKZ', name: 'Pakse International', city: 'Pakse', country: 'Laos' },
  { code: 'RGN', name: 'Yangon International', city: 'Yangon', country: 'Myanmar' },
  { code: 'MDL', name: 'Mandalay International', city: 'Mandalay', country: 'Myanmar' },
  { code: 'NYT', name: 'Nay Pyi Taw International', city: 'Nay Pyi Taw', country: 'Myanmar' },

  // South Asia — India, Pakistan, Nepal, Bangladesh, Sri Lanka, Maldives, Bhutan
  { code: 'DEL', name: 'Indira Gandhi International', city: 'Delhi', country: 'India' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International', city: 'Mumbai', country: 'India' },
  { code: 'BLR', name: 'Kempegowda International', city: 'Bangalore', country: 'India' },
  { code: 'MAA', name: 'Chennai International', city: 'Chennai', country: 'India' },
  { code: 'HYD', name: 'Rajiv Gandhi International', city: 'Hyderabad', country: 'India' },
  { code: 'CCU', name: 'Netaji Subhas Chandra Bose International', city: 'Kolkata', country: 'India' },
  { code: 'AMD', name: 'Sardar Vallabhbhai Patel International', city: 'Ahmedabad', country: 'India' },
  { code: 'PNQ', name: 'Pune', city: 'Pune', country: 'India' },
  { code: 'GOI', name: 'Dabolim', city: 'Goa', country: 'India' },
  { code: 'GOX', name: 'Manohar International', city: 'Goa', country: 'India' },
  { code: 'COK', name: 'Cochin International', city: 'Kochi', country: 'India' },
  { code: 'TRV', name: 'Trivandrum International', city: 'Thiruvananthapuram', country: 'India' },
  { code: 'CCJ', name: 'Calicut International', city: 'Kozhikode', country: 'India' },
  { code: 'IXM', name: 'Madurai', city: 'Madurai', country: 'India' },
  { code: 'TRZ', name: 'Tiruchirappalli International', city: 'Tiruchirappalli', country: 'India' },
  { code: 'CJB', name: 'Coimbatore International', city: 'Coimbatore', country: 'India' },
  { code: 'IXE', name: 'Mangaluru International', city: 'Mangalore', country: 'India' },
  { code: 'JAI', name: 'Jaipur International', city: 'Jaipur', country: 'India' },
  { code: 'LKO', name: 'Chaudhary Charan Singh International', city: 'Lucknow', country: 'India' },
  { code: 'VNS', name: 'Lal Bahadur Shastri International', city: 'Varanasi', country: 'India' },
  { code: 'PAT', name: 'Jay Prakash Narayan', city: 'Patna', country: 'India' },
  { code: 'GAU', name: 'Lokpriya Gopinath Bordoloi International', city: 'Guwahati', country: 'India' },
  { code: 'IMF', name: 'Imphal', city: 'Imphal', country: 'India' },
  { code: 'IXC', name: 'Chandigarh International', city: 'Chandigarh', country: 'India' },
  { code: 'ATQ', name: 'Sri Guru Ram Dass Jee International', city: 'Amritsar', country: 'India' },
  { code: 'SXR', name: 'Sheikh ul-Alam International', city: 'Srinagar', country: 'India' },
  { code: 'IXJ', name: 'Jammu', city: 'Jammu', country: 'India' },
  { code: 'IXL', name: 'Kushok Bakula Rimpochee', city: 'Leh', country: 'India' },
  { code: 'DED', name: 'Dehradun Jolly Grant', city: 'Dehradun', country: 'India' },
  { code: 'IXB', name: 'Bagdogra', city: 'Siliguri', country: 'India' },
  { code: 'BBI', name: 'Biju Patnaik International', city: 'Bhubaneswar', country: 'India' },
  { code: 'NAG', name: 'Dr. Babasaheb Ambedkar International', city: 'Nagpur', country: 'India' },
  { code: 'IDR', name: 'Devi Ahilya Bai Holkar', city: 'Indore', country: 'India' },
  { code: 'BHO', name: 'Raja Bhoj', city: 'Bhopal', country: 'India' },
  { code: 'RPR', name: 'Swami Vivekananda', city: 'Raipur', country: 'India' },
  { code: 'VTZ', name: 'Visakhapatnam International', city: 'Visakhapatnam', country: 'India' },
  { code: 'IXZ', name: 'Veer Savarkar International', city: 'Port Blair', country: 'India' },
  { code: 'AGX', name: 'Agatti', city: 'Agatti', country: 'India' },
  { code: 'KHI', name: 'Jinnah International', city: 'Karachi', country: 'Pakistan' },
  { code: 'LHE', name: 'Allama Iqbal International', city: 'Lahore', country: 'Pakistan' },
  { code: 'ISB', name: 'Islamabad International', city: 'Islamabad', country: 'Pakistan' },
  { code: 'PEW', name: 'Bacha Khan International', city: 'Peshawar', country: 'Pakistan' },
  { code: 'UET', name: 'Quetta International', city: 'Quetta', country: 'Pakistan' },
  { code: 'MUX', name: 'Multan International', city: 'Multan', country: 'Pakistan' },
  { code: 'SKT', name: 'Sialkot International', city: 'Sialkot', country: 'Pakistan' },
  { code: 'FSD', name: 'Faisalabad International', city: 'Faisalabad', country: 'Pakistan' },
  { code: 'KTM', name: 'Tribhuvan International', city: 'Kathmandu', country: 'Nepal' },
  { code: 'PKR', name: 'Pokhara International', city: 'Pokhara', country: 'Nepal' },
  { code: 'BWA', name: 'Gautam Buddha International', city: 'Bhairahawa', country: 'Nepal' },
  { code: 'DAC', name: 'Hazrat Shahjalal International', city: 'Dhaka', country: 'Bangladesh' },
  { code: 'CGP', name: 'Shah Amanat International', city: 'Chittagong', country: 'Bangladesh' },
  { code: 'ZYL', name: 'Osmani International', city: 'Sylhet', country: 'Bangladesh' },
  { code: 'CMB', name: 'Bandaranaike International', city: 'Colombo', country: 'Sri Lanka' },
  { code: 'HRI', name: 'Mattala Rajapaksa International', city: 'Hambantota', country: 'Sri Lanka' },
  { code: 'JAF', name: 'Jaffna International', city: 'Jaffna', country: 'Sri Lanka' },
  { code: 'MLE', name: 'Velana International', city: 'Malé', country: 'Maldives' },
  { code: 'GAN', name: 'Gan International', city: 'Addu City', country: 'Maldives' },
  { code: 'PBH', name: 'Paro International', city: 'Paro', country: 'Bhutan' },

  // Australia — domestic, regional and local
  { code: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australia' },
  { code: 'MEL', name: 'Melbourne Tullamarine', city: 'Melbourne', country: 'Australia' },
  { code: 'AVV', name: 'Melbourne Avalon', city: 'Melbourne', country: 'Australia' },
  { code: 'BNE', name: 'Brisbane', city: 'Brisbane', country: 'Australia' },
  { code: 'OOL', name: 'Gold Coast', city: 'Gold Coast', country: 'Australia' },
  { code: 'PER', name: 'Perth', city: 'Perth', country: 'Australia' },
  { code: 'ADL', name: 'Adelaide', city: 'Adelaide', country: 'Australia' },
  { code: 'CBR', name: 'Canberra', city: 'Canberra', country: 'Australia' },
  { code: 'HBA', name: 'Hobart', city: 'Hobart', country: 'Australia' },
  { code: 'LST', name: 'Launceston', city: 'Launceston', country: 'Australia' },
  { code: 'DRW', name: 'Darwin', city: 'Darwin', country: 'Australia' },
  { code: 'CNS', name: 'Cairns', city: 'Cairns', country: 'Australia' },
  { code: 'TSV', name: 'Townsville', city: 'Townsville', country: 'Australia' },
  { code: 'MKY', name: 'Mackay', city: 'Mackay', country: 'Australia' },
  { code: 'ROK', name: 'Rockhampton', city: 'Rockhampton', country: 'Australia' },
  { code: 'BDB', name: 'Bundaberg', city: 'Bundaberg', country: 'Australia' },
  { code: 'MCY', name: 'Sunshine Coast', city: 'Maroochydore', country: 'Australia' },
  { code: 'HTI', name: 'Hamilton Island', city: 'Hamilton Island', country: 'Australia' },
  { code: 'PPP', name: 'Proserpine Whitsunday Coast', city: 'Proserpine', country: 'Australia' },
  { code: 'ARM', name: 'Armidale', city: 'Armidale', country: 'Australia' },
  { code: 'NTL', name: 'Newcastle Williamtown', city: 'Newcastle', country: 'Australia' },
  { code: 'ABX', name: 'Albury', city: 'Albury', country: 'Australia' },
  { code: 'MIM', name: 'Merimbula', city: 'Merimbula', country: 'Australia' },
  { code: 'CFS', name: 'Coffs Harbour', city: 'Coffs Harbour', country: 'Australia' },
  { code: 'BWU', name: 'Bankstown', city: 'Sydney', country: 'Australia' },
  { code: 'WGA', name: 'Wagga Wagga', city: 'Wagga Wagga', country: 'Australia' },
  { code: 'ORA', name: 'Orange', city: 'Orange', country: 'Australia' },
  { code: 'DBO', name: 'Dubbo City Regional', city: 'Dubbo', country: 'Australia' },
  { code: 'TMW', name: 'Tamworth Regional', city: 'Tamworth', country: 'Australia' },
  { code: 'PLO', name: 'Port Lincoln', city: 'Port Lincoln', country: 'Australia' },
  { code: 'MHO', name: 'Mount House', city: 'Mount House', country: 'Australia' },
  { code: 'KGI', name: 'Kalgoorlie-Boulder', city: 'Kalgoorlie', country: 'Australia' },
  { code: 'BME', name: 'Broome', city: 'Broome', country: 'Australia' },
  { code: 'PHE', name: 'Port Hedland', city: 'Port Hedland', country: 'Australia' },
  { code: 'KTA', name: 'Karratha', city: 'Karratha', country: 'Australia' },
  { code: 'GET', name: 'Geraldton', city: 'Geraldton', country: 'Australia' },
  { code: 'EPR', name: 'Esperance', city: 'Esperance', country: 'Australia' },
  { code: 'ALH', name: 'Albany', city: 'Albany', country: 'Australia' },
  { code: 'KNX', name: 'Kununurra', city: 'Kununurra', country: 'Australia' },
  { code: 'MQL', name: 'Mildura', city: 'Mildura', country: 'Australia' },
  { code: 'MEB', name: 'Essendon Fields', city: 'Melbourne', country: 'Australia' },
  { code: 'ASP', name: 'Alice Springs', city: 'Alice Springs', country: 'Australia' },
  { code: 'AYQ', name: 'Ayers Rock Connellan', city: 'Uluru', country: 'Australia' },
  { code: 'GOV', name: 'Gove', city: 'Nhulunbuy', country: 'Australia' },
  { code: 'MCV', name: 'McArthur River Mine', city: 'Borroloola', country: 'Australia' },

  // New Zealand — domestic and regional
  { code: 'AKL', name: 'Auckland', city: 'Auckland', country: 'New Zealand' },
  { code: 'WLG', name: 'Wellington', city: 'Wellington', country: 'New Zealand' },
  { code: 'CHC', name: 'Christchurch', city: 'Christchurch', country: 'New Zealand' },
  { code: 'DUD', name: 'Dunedin', city: 'Dunedin', country: 'New Zealand' },
  { code: 'ZQN', name: 'Queenstown', city: 'Queenstown', country: 'New Zealand' },
  { code: 'HLZ', name: 'Hamilton', city: 'Hamilton', country: 'New Zealand' },
  { code: 'TRG', name: 'Tauranga', city: 'Tauranga', country: 'New Zealand' },
  { code: 'ROT', name: 'Rotorua Regional', city: 'Rotorua', country: 'New Zealand' },
  { code: 'NPE', name: 'Hawke\'s Bay', city: 'Napier', country: 'New Zealand' },
  { code: 'NSN', name: 'Nelson', city: 'Nelson', country: 'New Zealand' },
  { code: 'BHE', name: 'Woodbourne', city: 'Blenheim', country: 'New Zealand' },
  { code: 'IVC', name: 'Invercargill', city: 'Invercargill', country: 'New Zealand' },
  { code: 'PMR', name: 'Palmerston North', city: 'Palmerston North', country: 'New Zealand' },
  { code: 'GIS', name: 'Gisborne', city: 'Gisborne', country: 'New Zealand' },
  { code: 'WHK', name: 'Whakatane', city: 'Whakatane', country: 'New Zealand' },
  { code: 'KKE', name: 'Kerikeri', city: 'Kerikeri', country: 'New Zealand' },

  // Pacific Islands
  { code: 'NAN', name: 'Nadi International', city: 'Nadi', country: 'Fiji' },
  { code: 'SUV', name: 'Nausori', city: 'Suva', country: 'Fiji' },
  { code: 'APW', name: 'Faleolo International', city: 'Apia', country: 'Samoa' },
  { code: 'TBU', name: "Fua'amotu International", city: "Nuku'alofa", country: 'Tonga' },
  { code: 'VLI', name: 'Bauerfield International', city: 'Port Vila', country: 'Vanuatu' },
  { code: 'HIR', name: 'Honiara International', city: 'Honiara', country: 'Solomon Islands' },
  { code: 'POM', name: 'Port Moresby Jacksons International', city: 'Port Moresby', country: 'Papua New Guinea' },
  { code: 'LAE', name: 'Lae Nadzab', city: 'Lae', country: 'Papua New Guinea' },
  { code: 'RAB', name: 'Rabaul', city: 'Rabaul', country: 'Papua New Guinea' },
  { code: 'PPT', name: "Faa'a International", city: 'Papeete', country: 'French Polynesia' },
  { code: 'BOB', name: 'Bora Bora', city: 'Bora Bora', country: 'French Polynesia' },
  { code: 'MOZ', name: 'Moorea', city: 'Moorea', country: 'French Polynesia' },
  { code: 'INU', name: 'Nauru International', city: 'Yaren', country: 'Nauru' },
  { code: 'MJK', name: 'Shark Bay', city: 'Monkey Mia', country: 'Australia' },
  { code: 'CXI', name: 'Cassidy International', city: 'Kiritimati', country: 'Kiribati' },

  // Africa — North Africa
  { code: 'CAI', name: 'Cairo International', city: 'Cairo', country: 'Egypt' },
  { code: 'HRG', name: 'Hurghada International', city: 'Hurghada', country: 'Egypt' },
  { code: 'SSH', name: 'Sharm El Sheikh International', city: 'Sharm El Sheikh', country: 'Egypt' },
  { code: 'LXR', name: 'Luxor International', city: 'Luxor', country: 'Egypt' },
  { code: 'ASW', name: 'Aswan International', city: 'Aswan', country: 'Egypt' },
  { code: 'RMF', name: 'Marsa Alam International', city: 'Marsa Alam', country: 'Egypt' },
  { code: 'CMN', name: 'Mohammed V International', city: 'Casablanca', country: 'Morocco' },
  { code: 'RAK', name: 'Marrakesh Menara', city: 'Marrakesh', country: 'Morocco' },
  { code: 'FEZ', name: 'Fes-Saïss', city: 'Fes', country: 'Morocco' },
  { code: 'AGA', name: 'Al Massira', city: 'Agadir', country: 'Morocco' },
  { code: 'OUD', name: 'Angads', city: 'Oujda', country: 'Morocco' },
  { code: 'NDR', name: 'Al Hoceïma Cherif Al Idrissi', city: 'Al Hoceima', country: 'Morocco' },
  { code: 'TNG', name: 'Ibn Battouta', city: 'Tangier', country: 'Morocco' },
  { code: 'ALG', name: 'Houari Boumediene', city: 'Algiers', country: 'Algeria' },
  { code: 'ORN', name: 'Ahmed Ben Bella', city: 'Oran', country: 'Algeria' },
  { code: 'CZL', name: 'Mohamed Boudiaf International', city: 'Constantine', country: 'Algeria' },
  { code: 'TUN', name: 'Tunis-Carthage International', city: 'Tunis', country: 'Tunisia' },
  { code: 'MIR', name: 'Monastir Habib Bourguiba', city: 'Monastir', country: 'Tunisia' },
  { code: 'DJE', name: 'Zarzis', city: 'Djerba', country: 'Tunisia' },
  { code: 'TIP', name: 'Mitiga', city: 'Tripoli', country: 'Libya' },
  { code: 'BEN', name: 'Benina International', city: 'Benghazi', country: 'Libya' },
  { code: 'KRT', name: 'Khartoum International', city: 'Khartoum', country: 'Sudan' },

  // Africa — East Africa
  { code: 'ADD', name: 'Addis Ababa Bole International', city: 'Addis Ababa', country: 'Ethiopia' },
  { code: 'DIR', name: 'Aba Tenna Dejazmach Yilma', city: 'Dire Dawa', country: 'Ethiopia' },
  { code: 'NBO', name: 'Jomo Kenyatta International', city: 'Nairobi', country: 'Kenya' },
  { code: 'MBA', name: 'Mombasa Moi International', city: 'Mombasa', country: 'Kenya' },
  { code: 'WIL', name: 'Wilson', city: 'Nairobi', country: 'Kenya' },
  { code: 'KIS', name: 'Kisumu International', city: 'Kisumu', country: 'Kenya' },
  { code: 'DAR', name: 'Julius Nyerere International', city: 'Dar es Salaam', country: 'Tanzania' },
  { code: 'ZNZ', name: 'Abeid Amani Karume International', city: 'Zanzibar', country: 'Tanzania' },
  { code: 'JRO', name: 'Kilimanjaro International', city: 'Kilimanjaro', country: 'Tanzania' },
  { code: 'ARK', name: 'Arusha', city: 'Arusha', country: 'Tanzania' },
  { code: 'EBB', name: 'Entebbe International', city: 'Entebbe', country: 'Uganda' },
  { code: 'KGL', name: 'Kigali International', city: 'Kigali', country: 'Rwanda' },
  { code: 'BJM', name: 'Bujumbura International', city: 'Bujumbura', country: 'Burundi' },
  { code: 'DJI', name: 'Djibouti-Ambouli International', city: 'Djibouti', country: 'Djibouti' },
  { code: 'HGA', name: 'Egal International', city: 'Hargeisa', country: 'Somalia' },
  { code: 'MGQ', name: 'Aden Adde International', city: 'Mogadishu', country: 'Somalia' },
  { code: 'ASM', name: 'Asmara International', city: 'Asmara', country: 'Eritrea' },
  { code: 'SEZ', name: 'Seychelles International', city: 'Victoria', country: 'Seychelles' },
  { code: 'TNR', name: 'Ivato International', city: 'Antananarivo', country: 'Madagascar' },
  { code: 'NOS', name: 'Fascene', city: 'Nosy Be', country: 'Madagascar' },

  // Africa — West Africa
  { code: 'LOS', name: 'Murtala Muhammed International', city: 'Lagos', country: 'Nigeria' },
  { code: 'ABV', name: 'Nnamdi Azikiwe International', city: 'Abuja', country: 'Nigeria' },
  { code: 'KAN', name: 'Mallam Aminu International', city: 'Kano', country: 'Nigeria' },
  { code: 'PHC', name: 'Port Harcourt International', city: 'Port Harcourt', country: 'Nigeria' },
  { code: 'ACC', name: 'Kotoka International', city: 'Accra', country: 'Ghana' },
  { code: 'KMS', name: 'Kumasi', city: 'Kumasi', country: 'Ghana' },
  { code: 'ABJ', name: "Félix-Houphouët-Boigny International", city: 'Abidjan', country: 'Ivory Coast' },
  { code: 'DKR', name: 'Blaise Diagne International', city: 'Dakar', country: 'Senegal' },
  { code: 'DSS', name: 'Léopold Sédar Senghor', city: 'Dakar', country: 'Senegal' },
  { code: 'OUA', name: 'Ouagadougou International', city: 'Ouagadougou', country: 'Burkina Faso' },
  { code: 'BKO', name: 'Bamako-Sénou International', city: 'Bamako', country: 'Mali' },
  { code: 'NIM', name: 'Diori Hamani International', city: 'Niamey', country: 'Niger' },
  { code: 'NDJ', name: "N'Djamena International", city: "N'Djamena", country: 'Chad' },
  { code: 'CKY', name: 'Conakry International', city: 'Conakry', country: 'Guinea' },
  { code: 'FNA', name: 'Lungi International', city: 'Freetown', country: 'Sierra Leone' },
  { code: 'ROB', name: 'Roberts International', city: 'Monrovia', country: 'Liberia' },
  { code: 'LFW', name: 'Lomé-Tokoin', city: 'Lomé', country: 'Togo' },
  { code: 'COO', name: 'Cadjehoun', city: 'Cotonou', country: 'Benin' },
  { code: 'BJL', name: 'Banjul International', city: 'Banjul', country: 'Gambia' },
  { code: 'OXB', name: 'Osvaldo Vieira International', city: 'Bissau', country: 'Guinea-Bissau' },
  { code: 'RAI', name: 'Nelson Mandela International', city: 'Praia', country: 'Cape Verde' },

  // Africa — Central Africa
  { code: 'NSI', name: 'Yaoundé Nsimalen International', city: 'Yaoundé', country: 'Cameroon' },
  { code: 'DLA', name: 'Douala International', city: 'Douala', country: 'Cameroon' },
  { code: 'LBV', name: 'Léon-Mba International', city: 'Libreville', country: 'Gabon' },
  { code: 'BZV', name: 'Maya-Maya', city: 'Brazzaville', country: 'Republic of the Congo' },
  { code: 'PNR', name: 'Pointe-Noire', city: 'Pointe-Noire', country: 'Republic of the Congo' },
  { code: 'FIH', name: 'N\'djili International', city: 'Kinshasa', country: 'DRC' },
  { code: 'FBM', name: 'Lubumbashi International', city: 'Lubumbashi', country: 'DRC' },
  { code: 'SSG', name: 'Santa Isabel de Malabo', city: 'Malabo', country: 'Equatorial Guinea' },
  { code: 'BGF', name: 'Bangui M\'Poko International', city: 'Bangui', country: 'Central African Republic' },

  // Africa — Southern Africa
  { code: 'JNB', name: 'O. R. Tambo International', city: 'Johannesburg', country: 'South Africa' },
  { code: 'HLA', name: 'Lanseria International', city: 'Johannesburg', country: 'South Africa' },
  { code: 'CPT', name: 'Cape Town International', city: 'Cape Town', country: 'South Africa' },
  { code: 'DUR', name: 'King Shaka International', city: 'Durban', country: 'South Africa' },
  { code: 'PLZ', name: 'Chief Dawid Stuurman International', city: 'Port Elizabeth', country: 'South Africa' },
  { code: 'ELS', name: 'East London', city: 'East London', country: 'South Africa' },
  { code: 'BFN', name: 'Bram Fischer International', city: 'Bloemfontein', country: 'South Africa' },
  { code: 'GRJ', name: 'George', city: 'George', country: 'South Africa' },
  { code: 'MQP', name: 'Kruger Mpumalanga International', city: 'Nelspruit', country: 'South Africa' },
  { code: 'HDS', name: 'Hoedspruit Air Force Base', city: 'Hoedspruit', country: 'South Africa' },
  { code: 'WDH', name: 'Hosea Kutako International', city: 'Windhoek', country: 'Namibia' },
  { code: 'SWP', name: 'Swakopmund', city: 'Swakopmund', country: 'Namibia' },
  { code: 'GBE', name: 'Sir Seretse Khama International', city: 'Gaborone', country: 'Botswana' },
  { code: 'HRE', name: 'Robert Gabriel Mugabe International', city: 'Harare', country: 'Zimbabwe' },
  { code: 'BUQ', name: 'Joshua Mqabuko Nkomo International', city: 'Bulawayo', country: 'Zimbabwe' },
  { code: 'VFA', name: 'Victoria Falls International', city: 'Victoria Falls', country: 'Zimbabwe' },
  { code: 'LUN', name: 'Kenneth Kaunda International', city: 'Lusaka', country: 'Zambia' },
  { code: 'NLA', name: 'Simon Mwansa Kapwepwe International', city: 'Ndola', country: 'Zambia' },
  { code: 'LLW', name: 'Kamuzu International', city: 'Lilongwe', country: 'Malawi' },
  { code: 'MZM', name: 'Malawi International', city: 'Blantyre', country: 'Malawi' },
  { code: 'MPM', name: 'Maputo International', city: 'Maputo', country: 'Mozambique' },
  { code: 'BEW', name: 'Beira', city: 'Beira', country: 'Mozambique' },
  { code: 'MTS', name: 'King Mswati III International', city: 'Manzini', country: 'Eswatini' },
  { code: 'MSU', name: 'Moshoeshoe I International', city: 'Maseru', country: 'Lesotho' },
  { code: 'MRU', name: 'Sir Seewoosagur Ramgoolam International', city: 'Port Louis', country: 'Mauritius' },
  { code: 'RRG', name: 'Sir Charles Gaëtan Duval', city: 'Rodrigues', country: 'Mauritius' },
  { code: 'HAH', name: 'Prince Said Ibrahim International', city: 'Moroni', country: 'Comoros' },

  // Africa — Angola, Mozambique, Madagascar
  { code: 'LAD', name: 'Quatro de Fevereiro', city: 'Luanda', country: 'Angola' },
  { code: 'BUG', name: 'Benguela', city: 'Benguela', country: 'Angola' },
];

const normalize = (s: string) => s.toLowerCase().trim();

export function searchAirports(query: string, limit = 8): Airport[] {
  const q = normalize(query);
  if (!q) return [];
  const results: { airport: Airport; score: number }[] = [];
  for (const a of AIRPORTS) {
    const code = a.code.toLowerCase();
    const city = normalize(a.city);
    const country = normalize(a.country);
    const name = normalize(a.name);
    let score = 0;
    if (code === q) score = 100;
    else if (code.startsWith(q)) score = 90;
    else if (city === q) score = 85;
    else if (city.startsWith(q)) score = 80;
    else if (country === q) score = 70;
    else if (country.startsWith(q)) score = 65;
    else if (city.includes(q)) score = 50;
    else if (country.includes(q)) score = 40;
    else if (name.includes(q)) score = 30;
    if (score > 0) results.push({ airport: a, score });
  }
  results.sort((a, b) => b.score - a.score);
  return results.slice(0, limit).map((r) => r.airport);
}
