/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: '#00236f',
        'primary-container': '#1e3a8a',
        'on-primary': '#ffffff',
        'on-primary-container': '#90a8ff',
        'primary-fixed': '#dce1ff',
        secondary: '#4b41e1',
        'secondary-container': '#645efb',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#3323cc',
        tertiary: '#4b1c00',
        'tertiary-container': '#6e2c00',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f39461',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#773205',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#4059aa',
        'on-surface': '#191c1e',
        'on-surface-variant': '#444651',
        'on-background': '#191c1e',
        background: '#f7f9fb',
        outline: '#757682',
        'outline-variant': '#c5c5d3',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b6c4ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 32px 64px -15px rgba(30,58,138,0.04)',
        'card-md': '0 32px 64px -15px rgba(30,58,138,0.06)',
        topbar: '0 32px 64px -15px rgba(30,58,138,0.06)',
      },
    },
  },
  plugins: [],
}
